### ISSUE TITLE
Problem when making newsbeuter

### ISSUE THREAD

**Issue by yargy** [akrennmair/newsbeuter#108]
Hello,

I am using homebrew on macosx mavericks 10.9 and when it tries to make newsbeuter  there is an error that says:

==> make
#include <tr1/memory>
         ^
1 error generated.
make: *** [src/colormanager.o] Error 1
make: *** Waiting for unfinished jobs....

Does anyone know how to fix this?

**Comment by akrennmair** [comment]
The C++11 branch is now merged. This should fix all the OSX compilation problems you have experienced.
