### ISSUE TITLE
Deleting articles is extremely slow, if many articles in feed (was: "BULK-Delete" would be nice)

### ISSUE THREAD

**Issue by klartext** [akrennmair/newsbeuter#110]
In newsbeuter 2.7, when I delete many articles by pressing "D"-key for a while, the deleting is very slow.
It's an older/slower computer, but the problem is, I would guess, that each delete makes a single access to the sqlite-database. (connect,delete,disconnect)

It would be better, IMHO, if all delete-operations would be done just in mem, and when leaving a feed (or forcing an operation / syncing with database), that then all delete-operations will be done at once.

This would make the delete operations *much* faster.

**Comment by klartext** [comment]
My assumption, that there is database-access that makes the deletion slow was a wrong assumption.
The slowdown comes from handling the display!

I did profiling the nightmare of deleting about 1700 entries from a feed that had about 8500 entries.
It took about 1 second per entry (estimated, not measured).
So I need more time to delete the rest of the entries...

For comprison: Importing all 8542 entries from newsbeuter-sql-database into MariaDB took about 40 seconds on the same old machine with my selfwritten tool.

Most time is wasted in handling curses-display... see the excerpt from the profiling below:



=========================
Flat profile:

Each sample counts as 0.01 seconds.
  %   cumulative   self              self     total           
 time   seconds   seconds    calls   s/call   s/call  name    
 16.06     13.05    13.05 14698684     0.00     0.00  newsbeuter::fmtstr_formatter::do_wformat(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&, unsigned int)
  7.71     19.32     6.27     1793     0.00     0.04  newsbeuter::itemlist_formaction::prepare()
  6.99     25.00     5.68 45237978     0.00     0.00  newsbeuter::utils::strprintf[abi:cxx11](char const*, ...)
  6.72     30.46     5.46 117591295     0.00     0.00  newsbeuter::utils::str2wstr(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
  6.23     35.52     5.06 88195721     0.00     0.00  newsbeuter::fmtstr_formatter::register_fmt(char, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
  6.04     40.43     4.91 14696890     0.00     0.00  newsbeuter::utils::clean_nonprintable_characters(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >)
  5.27     44.71     4.28 233374097     0.00     0.00  void std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::_M_construct<wchar_t const*>(wchar_t const*, wchar_t const*, std::forward_iterator_tag)
  3.16     47.28     2.57 133592881     0.00     0.00  newsbeuter::openssl_mth_locking_function(int, int, char const*, int)
  3.01     49.73     2.45 117609743     0.00     0.00  newsbeuter::rss_item::has_attribute(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
  2.34     51.63     1.90 14696169     0.00     0.00  newsbeuter::utils::wtokenize(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >)
  2.33     53.52     1.89 14696166     0.00     0.00  newsbeuter::itemlist_formaction::gen_flags[abi:cxx11](std::shared_ptr<newsbeuter::rss_item>)
  2.25     55.35     1.83 29395574     0.00     0.00  newsbeuter::utils::wstr2str(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&)
  2.21     57.15     1.80 14698684     0.00     0.00  std::_Rb_tree<char, std::pair<char const, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >, std::_Select1st<std::pair<char const, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > > >, std::less<char>, std::allocator<std::pair<char const, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > > > >::_M_erase(std::_Rb_tree_node<std::pair<char const, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > > >*)
  2.03     58.80     1.65 18328814     0.00     0.00  std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release()
  1.66     60.15     1.35 14696890     0.00     0.00  newsbeuter::stfl::quote(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
  1.64     61.48     1.33 88218215     0.00     0.00  newsbeuter::itemlist_formaction::get_keymap_hint()
  1.56     62.75     1.27     4461     0.00     0.00  newsbeuter::rss_feed::unread_item_count()
  1.56     64.02     1.27 29396296     0.00     0.00  newsbeuter::utils::convert_text(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
  1.54     65.27     1.25 14698684     0.00     0.00  newsbeuter::fmtstr_formatter::do_format(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int)
  1.49     66.48     1.21    26444     0.00     0.00  void std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int>, std::allocator<std::pair

**Comment by Minoru** [comment]
Wow.

I don't see any way to really improve performance of `do_wformat`, but I'm investigating to see if I can at least call it less often.

**Comment by Minoru** [comment]
Tagging feature request was split out into #235.

**Comment by klartext** [comment]
@Minoru there is not any documentation on the function, but lets assume it formats a line, or all lines that are displayed...
...if it formats *all* lines, not only those that are really visible,
then it means doing work that is not necessary but eats up time.

I have 73 lines, and 73 * 117 = 8542.
If the algorithm is quadratic (just guessing), and we have 117 times more lines formatted than we needed, well, thats, why it's becoming slow...

So, I would guess, calling formatting functions only on the *really* displayed lines would help here.
I would suppose, something like a windowing could help here.

**Comment by Minoru** [comment]
FYI: it formats a line, yes. It is indeed called on all lines, not just
the visible ones, but that's only because we don't know which ones are
visible—STFL handles that stuff for us. The algorithm that calls
`do_format` is linear; `do_format` itself is amortized linear,
worst-case quadratic.

**Comment by Minoru** [comment]
Please try the code from `bugfix/110` branch.

**Comment by Minoru** [comment]
I guess we'll have to test this in production :)

**Comment by klartext** [comment]
Using a feed with 4052 items.
All items are marked read.

Then  deleting...

ORIG newsbeuter (newsbeuter 2.9):

  pressing "D" for about 20 sec.
  This deleted 1236 items.
  This took roughly 6 min 07

Then undeleted the items with pressing "D" again,
to have same conditions


FIXed newsbeuter ('bugfix/110' aka 0dfa9bb9b902688874643952fa551543adc75173):

  pressing "D" for about 20 sec.
  deleted 1242 items
  This took roughly 2 min 29
  
So, this looks much better now.
Think it can be seen as fixed.
Speed could be better, but the speed-problem seems not be related with deletion anymore (more general maybe; that would be a different issue then, not opened so far).

Thanks for fixing!

BTW:  
The fixed one also has different appearance in the feed-overview.
Wheras the 2.9 shows all feeds normal, the 'bugfix/110' shows
the feeds with unread items in bold.
Looks like the new behaviour is more accurate.

Guten Rutsch! :)

**Comment by Minoru** [comment]
That's great news! I've opened separate issue so that I don't forget to look deeper into performance issues once bug count is down to zero.

Feeds with unread items are highlighted because `listnormal_unread` and `listfocus_unread` now apply to feedlist as well (see #222).

Щасливого Нового року! ☺
