### ISSUE TITLE
segfault with current git-version

### ISSUE THREAD

**Issue by klartext** [akrennmair/newsbeuter#120]
Looking at the last of 10 feeds, got a crash.

used gdb to look at corefile...

================================
(gdb) core core.1170
[New LWP 1170]
[New LWP 1171]
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
warning: no loadable sections found in added symbol-file system-supplied DSO at 0x7fff3f9fe000
Core was generated by `newsbeuter'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f47e7fcf230 in std::string::c_str() const () from /usr/lib/libstdc++.so.6
(gdb) backtrace
#0  0x00007f47e7fcf230 in std::string::c_str() const () from /usr/lib/libstdc++.so.6
#1  0x000000000041c955 in newsbeuter::htmlrenderer::render_table (this=0x7fff3f9f6420, table=..., 
    lines=std::vector of length 42, capacity 64 = {...}) at src/htmlrenderer.cpp:807
#2  0x0000000000419ff4 in newsbeuter::htmlrenderer::render (this=0x7fff3f9f6420, input=..., 
    lines=std::vector of length 0, capacity 0, links=std::vector of length 4, capacity 4 = {...}, 
    url="http://www.mikrocontroller.net/feed/jobs") at src/htmlrenderer.cpp:494
#3  0x0000000000417e73 in newsbeuter::htmlrenderer::render (this=0x7fff3f9f6420, 
    source="\n<style type=\"text/css\">\n.ticmedizintechnik td {\n\twidth: 20%;\n}\n</style>\n<table class=\"ticmedizintechnik\">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td colspan=\"2\" rowspan=\"1\" style=\"height:2em;background-color:rgb(0.000000"..., lines=std::vector of length 0, capacity 0, 
    links=std::vector of length 4, capacity 4 = {...}, url="http://www.mikrocontroller.net/feed/jobs")
    at src/htmlrenderer.cpp:53
#4  0x00000000004979de in newsbeuter::itemview_formaction::render_html (this=0x1ca6130, 
    source="\n<style type=\"text/css\">\n.ticmedizintechnik td {\n\twidth: 20%;\n}\n</style>\n<table class=\"ticmedizintechnik\">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td colspan=\"2\" rowspan=\"1\" style=\"height:2em;background-color:rgb(0.000000"..., thelinks=std::vector of length 4, capacity 4 = {...}, 
    url="http://www.mikrocontroller.net/feed/jobs", render_width=107) at src/itemview_formaction.cpp:541
#5  0x0000000000493c98 in newsbeuter::itemview_formaction::prepare (this=0x1ca6130)
    at src/itemview_formaction.cpp:133
#6  0x000000000042c215 in newsbeuter::view::run (this=0x7fff3f9f7050) at src/view.cpp:166
#7  0x0000000000441737 in newsbeuter::controller::run (this=0x7fff3f9f7180, argc=1, argv=0x7fff3f9f7588)
    at src/controller.cpp:610
#8  0x0000000000408682 in main (argc=1, argv=0x7fff3f9f7588) at newsbeuter.cpp:30
(gdb) 
================================

The feed is mentioned above in the gdb-output.
It was the first entry that crashed. Looking at other
entries did not create a crash.
If you want to test, try the entry
"1 N  Feb 09   4.2K  Stellenangebot: Ingenieur Elektrotechnik FH/TH (m/w) / Elektroniker (m/w) (tic Medizinte"
#Newsbeuter 2.7 does not crash, I tried it with the same feed/message.

**Comment by Minoru** [comment]
Sorry I got to this issue so late. The item you're referencing already expired, and I can't reproduce the problem. Did you experience it recently with any other feed?

**Comment by klartext** [comment]
I could not reproduce with other feeds in any time. This was only
that one post on that one feed - and with the newsbeuter I used at these days.
(Don't know which version I used back then, I think it was official release for Arch, maybe newsbeuter 2.9, or was it 2.9?)
I doubt, that the old rss-entrie will be available anymore...
So reproducing that crash seems to be hard / nearly impossible.

**Comment by Minoru** [comment]
I see. Well, let's wait for someone else to bump into it and report again, then :(

Thank you for the original report, though; if only I got to it in time…
