### ISSUE TITLE
Feature Request: Owncloud News Sync

### ISSUE THREAD

**Issue by cwmke** [akrennmair/newsbeuter#134]
I'm wondering if there's any chance of adding Owncloud News syncing with Newsbeuter.  Thanks.

**Comment by mrbiber** [comment]
https://www.bountysource.com/issues/2110146-feature-request-owncloud-news-sync

**Comment by dirb** [comment]
I'm working on that in this branch
https://github.com/dirb/newsbeuter/tree/ocnews-support

**Comment by Minoru** [comment]
Oh, cool! Please note that I mean to release 2.10 soon, so this feature will be merged into 2.11 even if you submit a PR before 2.10 release.

By the way, you're using spaces for indentation, while the rest of the project uses tabs. Also, we're putting a single space after keywords like `if` and `while` to differentiate them from functions. You can quickly reformat things by running `make fmt`, but don't apply its suggestions blindly—it tends to make a mess of wrapped lines, for example. Anyway, don't worry too much about it, as I'll be doing a review of your PR anyway and will catch stuff like that.

**Comment by dirb** [comment]
Oh, my bad about that, I was using QtCreator and I didn't notice that were tabs and not spaces :P
I just correct that.
