### ISSUE TITLE
src/configcontainer.cpp:21:15: warning: 'va_start' has undefined behavior with reference types [-Wvarargs]

### ISSUE THREAD

**Issue by dcb314** [akrennmair/newsbeuter#135]
Source code is

configdata::configdata(const std::string& v, ...) : value(v), default_value(v), type(ENUM) {
    va_list ap;
    va_start(ap, v);

**Comment by akrennmair** [comment]
Fixed in latest revision.

**Comment by ahitrin** [comment]
Fine, thanks!
