### ISSUE TITLE
<dc:creator> is ignored in certain feeds

### ISSUE THREAD

**Issue by Etn40ff** [akrennmair/newsbeuter#143]
Hi, 
I am new to newsbeuter.
I am trying to load news from arxiv (http://export.arxiv.org/rss/math.QA) but it looks like the author field does not get filled by the <dc:creator> fields. Am I missing something?
Thanks

**Comment by soundsc** [comment]
Hi, according to the [RSS 1.0 specification](http://web.resource.org/rss/1.0/modules/dc/) (and my personal experience with the 13 feeds I'm subscribing), the field in question should be `dc:creator` rather than just `creator`. For me, this still results in authors not being shown.

**Comment by soundsc** [comment]
Cannot reproduce this problem with latest master after all, author field seems to get filled alright. I think I observed this with 2.10-cffd but it seems to have been solved. Closing pull request. Sorry for the distraction!

**Comment by Minoru** [comment]
No worries; thanks for caring in the first place!
