### ISSUE TITLE
Old Reader passwordfile crash

### ISSUE THREAD

**Issue by keith** [akrennmair/newsbeuter#149]
I'm getting this crash when attempting use use The Old Reader passwordfile option

```
Loading URLs from The Old Reader...newsbeuter(80903,0x7fff78662310) malloc: *** error for object 0x7fff788fc068: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
```

This is on OS X 10.9 installed from homebrew. Also it works fine using `oldreader-password`. In the meantime I'm using an `include` that has that password definition to keep it out of my dotfiles.

**Comment by Minoru** [comment]
@keith, do you experience the issue with 2.9?

**Comment by keith** [comment]
I am actually using newsbeuter with a different service now. Hopefully someone else can chime in on if this is still an issue.

**Comment by Minoru** [comment]
Oh, okay. I guess people would've reported it already if anyone else run into it, so I'm going to close the issue.

**Comment by keith** [comment]
Thanks!
