### ISSUE TITLE
Old Reader URL loading error

### ISSUE THREAD

**Issue by keith** [akrennmair/newsbeuter#150]
After downloading your feeds from the old reader everything works fine. Then after closing and reopening newsbeuter a few times there starts to be errors when refreshing feeds:

```
[2014-09-07 01:11:07] Error while retrieving http://theoldreader.com/reader/atom/feed/randomcharacters?n=20: HTTP response code said error
```

This seems to be being printed from [here](https://github.com/akrennmair/newsbeuter/blob/1427bdb0705806368db39576a9b803df82fa0415/src/controller.cpp#L751-L752) (I threw in some logging to make sure).

These errors occur for all feeds until deleting the `cache.db` file. I've checked the URLs afterwards and found that they are still active and accessible with valid credentials.

**Comment by wedens** [comment]
same problem

**Comment by teffalump** [comment]
Same

**Comment by moon-musick** [comment]
Same problem.

**Comment by tka1** [comment]
Same here. Is it some problem with TOR api rate limitations?

**Comment by Fraterius** [comment]
The same here, some patch or simple walk around would be great.

**Comment by Minoru** [comment]
The problem lied with `curl_easy_setopt(…, CURLOPT_HTTPHEADER, …)`. It *sets* HTTP headers, not *appends* new to existing ones. So when Old Reader API module tried to set `ETag` header, it accidentally removed `Authorization`, which, unsurprisingly enough, resulted in errors.

This has been fixed now, and I can no longer reproduce the problem. A couple confirmations from users would be great. Thank you for flying Newsbeuter!

**Comment by moon-musick** [comment]
Seems to be working indeed. Compiled in Ubuntu 14.04 amd64, installed as a deb file in another Ubuntu machine, no unpleasant surprises so far (after a few hours of usage). Thank you :)

**Comment by Minoru** [comment]
Yay! Good to know, thanks for reporting back.
