### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by simonnagl** [akrennmair/newsbeuter#151]
I am using newsbeuter in my update script to check some feeds for news before updating.
Thant works fine with the -x options.
Would it be possible to implement a option to directly print the unread messages to stdout without starting the "front end"?

**Comment by Minoru** [comment]
Original problem sounds like a job for rsstail, not Newsbeuter.

As for more `-x` commands, including custom ones, this might be added in the future, but currently we don't consider any such ideas.
