### ISSUE TITLE
Viewing an atom feed item with base64-encoded inline image data makes newsbeuter hang at 100% CPU load

### ISSUE THREAD

**Issue by wasamasa** [akrennmair/newsbeuter#154]
I've encountered an issue with [this atom feed](http://jvns.ca/atom.xml) and more specifically the feed item corresponding to [this post](http://jvns.ca/blog/2014/07/11/fun-with-stats-how-big-of-a-sample-size-do-i-need/). When hitting the return key this operation makes newsbeuter hang up completely. Upon inspecting it a closer look revealed the only potentially problematic looking thing I've found was the fact the `img` tags use base64-encoded image data. Even just viewing it in Emacs made it abort syntax highlighting of the part in question.

Removing the contents of the `src` attribute in the problematic `img` tags of a locally saved version of the feed fixed the issue for me. I concur it must be something with their contents that causes the high CPU load.

edit: Perhaps issue #85 is related.

**Comment by antoyo** [comment]
I'm not sure if it is the same issue, but I get the same problem with this feed:
"[okucbyxc] Happy 2015!" on http://planet.haskell.org/atom.xml
but it does not seem to have any image in it.
