### ISSUE TITLE
Whole feeds marked as unread

### ISSUE THREAD

**Issue by du5tball** [akrennmair/newsbeuter#164]
As of version 2.9, newsbeuter sometimes marks hundreds of posts (whole feeds) as unread when I update via newsbeuter -x reload (or even shift+r from within newsbeuter). More often than not, this seems to target feeds with attachments. Mostly podcasts, but some comics get reset too every few updates.

**Comment by trUSTssc** [comment]
The bug was introduced in 1427bdb0705806368db39576a9b803df82fa0415.

Current git + this patch fixes it.
```
diff --git a/src/controller.cpp b/src/controller.cpp
index 4147909..ad7358b 100644
--- a/src/controller.cpp
+++ b/src/controller.cpp
@@ -721,7 +721,6 @@ void controller::reload(unsigned int pos, unsigned int max, bool unattended, cur
 			if (newfeed->items().size() > 0) {
 				std::lock_guard<std::mutex> feedslock(feeds_mutex);
 				save_feed(newfeed, pos);
-				enqueue_items(newfeed);
 
 				newfeed->clear_items();
 
@@ -730,6 +729,7 @@ void controller::reload(unsigned int pos, unsigned int max, bool unattended, cur
 				feed->set_tags(urlcfg->get_tags(oldfeed->rssurl()));
 				feed->set_order(oldfeed->get_order());
 				feeds[pos] = feed;
+				enqueue_items(feed);
 
 				oldfeed->clear_items();
 
```

**Comment by Minoru** [comment]
Since I have no way of reproducing this, I'll apply your patch blindly and just see where it gets us :) Thanks to both of you for reporting and fixing, accordingly.

**Comment by trUSTssc** [comment]
This solves the issue. :)

However since the patch was applied a bit too blindly it was not the one provided (note ```newfeed``` vs. ```feed```) and another bug was introduced. This prevents the podcast URLs from being added (using ```podcast-auto-enqueue yes```) to ```/path/to/config/dir/queue``` where they can be picked up by podbeuter.

**Comment by Minoru** [comment]
That's embarrassing. Thanks for being so patient with me.

**Comment by trUSTssc** [comment]
No problem. Thanks for taking care of the project! :)

**Comment by Minoru** [comment]
JFTR, this patch also fixed another bug, one where previously enqueued enclosures were enqueued again if removed from the queue file (reported by @tsipinakis).
