### ISSUE TITLE
newsbeuter 2.9: Multiple "highlight article" don't work correctly. Only the first "highlight article" take effect.

### ISSUE THREAD

**Issue by yang-ling** [akrennmair/newsbeuter#166]
Hi. Newsbeuter is my favorite RSS reader and recently I upgrade it to 2.9, but I have problems with *highlight article* config.

Say I have a "highlight article" config like this:

`highlight article     "^(Feed|Title|Author|Link|Date):.*"   black white`

And it works fine.

![newsbeuter-bug-1](https://cloud.githubusercontent.com/assets/1992391/6389254/7cc80412-bddd-11e4-961e-c82c38e48163.png)

Then I want links to have blue color, so my config becomes like this:

```
highlight article     "^(Feed|Title|Author|Link|Date):.*"   black white
highlight article     "\\[[0-9][0-9]*\\]"                   blue  default  bold
```

It doesn't work fine.

![newsbeuter-bug-2](https://cloud.githubusercontent.com/assets/1992391/6389359/63c32f40-bdde-11e4-8898-b6a7cfa7a695.png)

It seems that **fgcolor**, **bgcolor** and **attributes** of the first *highlight article* are overwritten by the second *highlight article*'s, and the second *highlight article*'s regex doesn't take effect.

And If I remove the first *highlight article*, then second one works fine.

`highlight article     "\\[[0-9][0-9]*\\]"                   blue  default  bold`

Output
![newsbeuter-bug-3](https://cloud.githubusercontent.com/assets/1992391/6389501/4923e8b8-bddf-11e4-9647-3873dac88bac.png)

Here is my full color config

```
highlight feedlist    "^  *[0-9]+  *N  "                    color156 default
highlight articlelist "^  *[0-9]+  *N  "                    color156 default

highlight article     "^(Feed|Title|Author|Link|Date):.*"   color75  default
highlight article     "^Podcast Download URL:.*"            color71  default
highlight article     "^Links:"                             white    color240 underline
highlight article     "\\[[0-9][0-9]*\\]"                   color72  default  bold
highlight article     "\\[image [0-9][0-9]*\\]"             color72  default  bold
highlight article     "\\[embedded flash: [0-9][0-9]*\\]"   color72  default  bold
highlight article     ":.*\\(link\\)$"                      color74  default
highlight article     ":.*\\(image\\)$"                     color74  default
highlight article     ":.*\\(embedded flash\\)$"            color74  default

color listnormal color244 color234
color listnormal_unread color244 color234 bold
color listfocus  color166 color235
color info       color136 color235
color background color244 color234
color article    color244 color234
```

And output is
![newsbeuter-bug-4](https://cloud.githubusercontent.com/assets/1992391/6389608/73d46a5a-bde0-11e4-86bf-426a037465c4.png)

You can see *highlight article* doesn't work as expected.
I feel newsbeuter uses the **regex** of the first *highlight article* and use the **fgcolor**, **bgcolor**, **attributes** of the last *highlight article*.
All other *highlight article* config don't take effect.

Hope I have explained this issue clear enough.

My full config file is [here](https://gist.github.com/yang-ling/129d3125d53b2caa6ea1#file-newsbeuter-config). If it is not bug but fault of my config file, please correct me. Thanks!

Environment information:

* newsbeuter 2.9
* OS: Archlinux
* Terminal emulator: terminator 0.97, also test on konsole, same problems

**Comment by brianbuccola** [comment]
I can confirm that version 2.9 breaks highlighting. I have the following set (plus a few others for special keywords):

    highlight   article "^Feed:"      magenta     default     bold
    highlight   article "^Title:"     green       default     bold
    highlight   article "^Author:"    default     default     bold
    highlight   article "^Link:"      cyan        default     bold
    highlight   article "^Date:"      red         default     bold

In 2.9, however, only "Feed" gets highlight, *and* for some reason it's always highlighted red, even if I have it set to magenta, green, etc.

Downgrading to 2.8 fixes the issue, so something must be different in 2.9.

Note: Highlighting is broken both in the official Arch Linux [community] binary and in the development version of newsbeuter (git).

**Comment by sharethewisdom** [comment]
I can also confirm this. (on Arch)

**Comment by clauseggers** [comment]
Exact same issue here. Also the term-colors are not the right ones in all instances. Many of the colors are off what they should be by some measure, and others are completely wrong.

**Comment by dahu** [comment]
The named term-colors are still wrong in 2.10.

**Comment by Kaligule** [comment]
can cofirm on Arch with Version 2.9

**Comment by Kaligule** [comment]
I did a ```git bisect``` on this and found that this is the first commit where the error occurs:
```
commit a3106ff155a7a89d80e50e8aed4ef20a55b0aa72
Author: Andreas Krennmair <ak@synflood.at>
Date:   Tue Feb 17 09:59:58 2015 +0100

    merge C++11 support.
```

**Comment by pickfire** [comment]
Yeah, I seem to found this bug on arch linux, is it fixed?

**Comment by Kaligule** [comment]
No, this bug is not fixed.

**Comment by pickfire** [comment]
Is `newsbeuter` unmaintained currently?

**Comment by akrennmair** [comment]
@pickfire no, I'm just super busy with my current job. I simply have neither the time nor the energy to put any more effort into newsbeuter.

**Comment by pickfire** [comment]
@akrennmair Sorry, if I had insulted anyone. Is there any other mainainer other than you (collaborator)?

**Comment by yang-ling** [comment]
@pickfire [Check here](https://github.com/akrennmair/newsbeuter/graphs/contributors)
No active contributor now(2015) other than @akrennmair

**Comment by pickfire** [comment]
I hope I can help to contribute to it but I doesn't know any c++. I will try to take a look into it.

**Comment by pickfire** [comment]
I think I had found something that may break the multiple highlight article:
```diff
index 0f94567..eb21d87 100644
--- a/src/colormanager.cpp
+++ b/src/colormanager.cpp
@@ -67,12 +67,11 @@ void colormanager::handle_action(const std::string& action, const std::vector<st
 }

 void colormanager::dump_config(std::vector<std::string>& config_output) {
-   for (std::map<std::string, std::string>::iterator it=fg_colors.begin();it!=fg_colors.end();++it) {
-           std::string configline = utils::strprintf("color %s %s %s", it->first.c_str(), it->second.c_str(), bg_colors[it->first].c_str());
-           std::vector<std::string> attribs = attributes[it->first];
-           for (std::vector<std::string>::iterator jt=attribs.begin();jt!=attribs.end();++jt) {
+ for (auto color : fg_colors) {
+         std::string configline = utils::strprintf("color %s %s %s", color.first.c_str(), color.second.c_str(),
bg_colors[color.first].c_str());
+         for (auto attrib : attributes[color.first]) {
                        configline.append(" ");
-                   configline.append(*jt);
+                 configline.append(attrib);
                }
                config_output.push_back(configline);
        }
```
I does not fully understand what it does, but of all the others, it seems weird to me.

**Comment by Kaligule** [comment]
@pickfire [A mutex is a thing used when you do multithreading](http://www.cplusplus.com/reference/mutex/mutex/). Roughly said, if a process edits some files it must make sure that no other process is editing them at the same time. So it adds a "busy"-sign to the file, does the editing and then removes it so other processes can go for it.

**Comment by pickfire** [comment]
It seems like most of the commit is syntax correction and there is some changes for the code. Does listing the changes helps in fixing the bug?
