### ISSUE TITLE
SSL connect error

### ISSUE THREAD

**Issue by takiz** [akrennmair/newsbeuter#171]
ERROR: rsspp::parser::parse_url: curl_easy_perform returned err 35: SSL connect error
USERERROR: Error while retrieving https://navalny.com/blog/post.rss: SSL connect error

But other rss-readers work ok.

P.S  Ubuntu 14.04 LTS with lastest updates, newsbeuter from git.

**Comment by akrennmair** [comment]
Can't reproduce, neither on Debian nor on Mac OS X. Is this error persisting? What's the output of "newsbeuter -v"?

**Comment by takiz** [comment]
Compilation date/time: Mar 24 2015 23:33:07
System: Linux 3.19.2 (i686)
Compiler: g++ 4.8.2
ncurses: ncurses 5.9.20140118 (compiled with 5.9)
libcurl: libcurl/7.35.0 GnuTLS/2.12.23 zlib/1.2.8 libidn/1.28 librtmp/2.3 (compiled with 7.35.0)
SQLite: 3.8.2 (compiled with 3.8.2)
libxml2: compiled with 2.9.1

On the other machine with newest Ubuntu 14.10 works fine, but Ubuntu 14.04 LTS give ssl error.

**Comment by takiz** [comment]
I solved this problem after update GnuTLS

>$  newsbeuter -v | grep -i GnuTLS
libcurl: libcurl/7.35.0 GnuTLS/3.2.11 zlib/1.2.8 libidn/1.28 librtmp/2.3 (compiled with 7.35.0)

**Comment by akrennmair** [comment]
OK, thanks.
