### ISSUE TITLE
Stuck at "Loading URLs from Tiny Tiny RSS..."

### ISSUE THREAD

**Issue by Hund** [akrennmair/newsbeuter#172]
When I start Newsbeuter it gets stuck at "Loading URLs from Tiny Tiny RSS...":

>XDG: configuration directory '/home/johan/.config/newsbeuter' not accessible, using '/home/johan/.newsbeuter' instead.
>Starting newsbeuter 2.9...
>Loading configuration...done.
>Opening cache...done.
>Loading URLs from Tiny Tiny RSS...

I'm running Newsbeuter 2.9-1 from Arch Linux own repo. And here is the log from "newsbeuter -l6 -d debug.log": http://pastebin.com/wWKGNa8V

**Comment by nedson** [comment]
ditto. Getting this message using Raspian and Newsbeuter 2.5.

**Comment by Minoru** [comment]
@Hund, what version of TT-RSS are you using? Do you even experience the issue (it's been a few months now...)

@nedson, TT-RSS completely switched to JSON API way back in 2012; Newsbeuter only gained support for it in 2.6. Either roll back your TT-RSS installation or upgrade your Newsbeuter.

**Comment by gs93** [comment]
@Minoru tt-rss switched to a [rolling release system](https://tt-rss.org/forum/viewtopic.php?f=10&t=3262) (NB and tt-rss on HEAD works for me).

**Comment by Minoru** [comment]
Oh, thanks for the head-up! I'll accept the commit SHA1 as the version number, then :)

**Comment by Hund** [comment]
I dont use TT-RSS anymore. I couldn't find a decent client for Android. :( Thats where I do most of my reading.

**Comment by Minoru** [comment]
Guess I'll just close the issue then. Thanks for reporting this, though, and sorry we couldn't solve your problem while it still existed.

**Comment by Hund** [comment]
I'm back with ttrss and I still have the same issue. :( I'm using ttrss 1.15.

**Comment by Minoru** [comment]
Can you try running this and show me the output?

`curl -d '{"op":"login","user":"USERNAME","password":"PASSWORD"}' URL/api/`

URL is what you put in `ttrss-url` setting in your config.

**Comment by Hund** [comment]
I think I found the issue. It was my password being to complex? I changed to a super simple password and then it worked.

**Comment by Minoru** [comment]
Oh! Did your previous password contain double quotes (`"`)?

**Comment by Hund** [comment]
It did. I never noticed it. :)

**Comment by Minoru** [comment]
JFTR, quotes can be escaped. See 19d3f717c9b58d5d1c144c8918554f04a207dfbb.
