### ISSUE TITLE
Can't change color for the current selected unread feed in feedlist.

### ISSUE THREAD

**Issue by rfegq4** [akrennmair/newsbeuter#173]
Hi guys,

I'm trying to change the color for the current selected unread feed, but as far as I know, this is not possible with the current elements: listnormal, listfocus. I expected the element "listfocus unread", but this is unfortunately not present.

PS
I'm using newsbeuter 2.7.

**Comment by Duncanla** [comment]
This feature was added in 2.7. You are looking for the listnormal_unread and listfocus_unread elements.

Reference:
https://newsbeuter.org/doc/newsbeuter.html#_configuring_colors

**Comment by Minoru** [comment]
Hooray for users supporting other users! Thank you, @Duncanla.
