### ISSUE TITLE
[Feature Request] Display inline images

### ISSUE THREAD

**Issue by pickfire** [akrennmair/newsbeuter#184]
I uses `newsbeuter` but I would like it to display **inline images** like how `w3m` displaying images in the default internal renderer.

**Comment by benoliver999** [comment]
I'd like to chime in and also add interest in this feature.

**Comment by pickfire** [comment]
`w3m` uses **imlib2** to display inline images but it only works on `xterm` and it is a bit buggy on `urxvt` and `st`.

**Comment by benoliver999** [comment]
Yeah I've seen it in ranger on urxvt. Works pretty well but as you say, it can be a little buggy. Is there an easy way to implement it just locally? I'm new to newsbeuter and don't know how configurable it is.

**Comment by pickfire** [comment]
I don't know much about newsbeuter too, I think that they have their issue tracker at google code (I have posted some issues but no reply yet).

**Comment by Minoru** [comment]
Sorry, people, but that's not gonna happen. This FR represents a feature creep; implement it, and next thing you know, someone's wondering why newsbeuter is lacking full HTML5 support. Just use the browser, or maybe an image viewer that supports URLs.
