### ISSUE TITLE
website down :'(

### ISSUE THREAD

**Issue by k0377** [akrennmair/newsbeuter#187]
what happened to newsbeuter.org? no more documentation available (apart from this repo) :crying_cat_face:

**Comment by simonnagl** [comment]
I can reproduce this

**Comment by akrennmair** [comment]
Fixed. I did an apt-get upgrade on the server and forgot it was interactive, so it had shut down lighttpd, and then asked me about something...

**Comment by k0377** [comment]
Awesome! :kissing_cat: I thought newsbeuter is dead. :D
