### ISSUE TITLE
folder support for ttrss

### ISSUE THREAD

**Issue by k0377** [akrennmair/newsbeuter#188]
When I sync with tiny tiny rss, there are no folders but only a flatten list of my feeds. Some tree view would be nice or at least an alternative view. Maybe like cmus does, where u can cycle trough different kind of views with 1-6.

**Comment by ntnn** [comment]
@k0377 You can 'sort' by tags and the tags are ttrss' folders. `t` to see the list of tags, `T` to clear the current tag.

However a tree view or something like that would really be nice.

**Comment by ntnn** [comment]
The folders are parsed as tags, and you can sort the feeds after tags (press `t`).

**Comment by Minoru** [comment]
@k0377, I believe the issue is resolved. Please re-open if it isn't so.

**Comment by The-Compiler** [comment]
Whoaaa, this is awesome! I think this should be documented in the [TTRSS sync chapter](http://www.newsbeuter.org/doc/newsbeuter.html#_tiny_tiny_rss_synchronization) though - I'd never have discovered that if it wasn't for this issue :smile:

**Comment by Minoru** [comment]
Good point! I'll open another issue for that.
