### ISSUE TITLE
The Old Reader folders are not available as tags

### ISSUE THREAD

**Issue by apheleia** [akrennmair/newsbeuter#189]
## What steps will reproduce the problem?
1. set up login using The Old Reader credentials as docs described
2. start newsbeuter and load feeds
3. try to select tag by pressing `t`

## What is the expected output?
tags should be shown (one for each folder)

## What do you see instead?
instead, it reads `No tags defined.`

## What version of the product are you using? On what operating system?
newsbeuter 2.9 latest master (125afcd61a)
ubuntu 14.04

**Comment by rafaeln** [comment]
I've had the same problem. But it looks like this issue has been open for six months...

**Comment by Minoru** [comment]
I just haven't got around to checking if it's still reproducible and then fixing it, that's all.

**Comment by rafaeln** [comment]
I hope you find time to check this out, @Minoru, and thanks for the great piece of software. On a related topic, a maybe undocumented feature of Newsbeuter is that the `urls` file is still active even if the source of feeds is *TheOldReader*. In particular, I use the following `urls` file:

    "query:Unread Articles:unread = \"yes\""
    "query:Read Articles:unread = \"no\""

My question is if, as a workaround, it would be possible to attribute tags to the feeds from *TheOldReader* in my `urls` file as well.

**Comment by Minoru** [comment]
All thanks are due to Andreas Krennmair; all I do is introduce new bugs :)

> a maybe undocumented feature of Newsbeuter is that the urls file is still active even if the source of feeds is TheOldReader

Hmm, that indeed was undocumented. Thanks for the pointer! Does an updated doc (see commit 5da8a638ee4ca3b05021e1c27cdfd6209f022f27) make sense?

> if, as a workaround, it would be possible to attribute tags to the feeds from TheOldReader in my urls file

Not at the moment, and I don't think it's a good idea to implement something like this—it only makes managing your tags harder, because now you have two places to look after.

**Comment by rafaeln** [comment]
I see why it wouldn't be a good idea to allow the workaround I suggested. If you don't try to keep your code logic clean, you can end up with something live `vim`!

I took a look at the documentation change and I think it pretty much documents the undocumented feature I had found. Related to that undocumented feature, only the `urls` file is ever read, even if I ask for `newsbeuter` to read from another urls file with `-u otherurlsfile`.

**Comment by Minoru** [comment]
> Related to that undocumented feature, only the `urls` file is ever read, even if I ask for `newsbeuter` to read from another urls file with `-u otherurlsfile`

I couldn't reproduce that with HEAD. Can you open an issue describing precisely what you're doing?

On the upside, I also checked the bug we're supposed to be discussing here :) That one I reproduced and even fixed. Please test!

**Comment by rafaeln** [comment]
Thanks for the fixes. Now I am getting tags from *TheOldReader*, and I am also able to indicate the path to my `urls` file on the commandline with the `-u` option.
