### ISSUE TITLE
age filter doesn't seem to work in query feeds

### ISSUE THREAD

**Issue by gpakosz** [akrennmair/newsbeuter#194]
Hello,

I'm using the following query feeds:

    "query:Unread Articles:unread = \"yes\" and tags !# \"foo\" and tags !# \"bar\""
    "query:Unread Articles (this year):unread = \"yes\" and tags !# \"foo\" and tags !# \"bar\" and age between 0:365"

which returns no item:

    1 N (4404/4407) Unread Articles
              (0/0) Unread Articles (this year)

If I do:

    "query:Unread Articles (this year):unread = \"yes\" and tags !# \"foo\" and tags !# \"bar\" and (age between 0:365)"

I'm getting the following:

    1 N (5380/37610 Unread Articles (this year)
    2 N (4404/4407) Unread Articles

The display is broken (missing parenthesis) and the counts don't make sense at all.
As you can see, Newsbeuter believes there are more unread article with age between 0 and 365 than there are unread articles in total.

**Comment by Minoru** [comment]
I don't know where insane numbers are coming from—I couldn't reproduce this part.

The error, though, was fixed. Can you compile current HEAD and test?

**Comment by gpakosz** [comment]
Seems to work. Thanks!
