### ISSUE TITLE
newsbeuter - ncurses 6.0

### ISSUE THREAD

**Issue by sdoubleyou** [akrennmair/newsbeuter#206]
after last ncurses Update 6.0 newsbeuter can't start.
newsbeuter: error while loading shared libraries: libncursesw.so.5: cannot open shared object file: No such file or directory

**Comment by The-Compiler** [comment]
duplicate of #198

**Comment by sdoubleyou** [comment]
yes sure, i thinek, with Arch/Manjaro we need a new git-Version in the packages

**Comment by The-Compiler** [comment]
Arch already has a patch for the issue

**Comment by sdoubleyou** [comment]
yes :+1:  Manjaro 1 hour later :-)
