### ISSUE TITLE
Retrieve full article upon encountering 'continue' link

### ISSUE THREAD

**Issue by cilia** [akrennmair/newsbeuter#209]
Some feeds only provide the beginning part(s) of an article followed by some sort of 'continue' link to the actual web page. Is it possible to make newsbeuter retrieve the full article using this link automatically?

**Comment by e0i** [comment]
Although not exactly the answer you're looking for, you might be interested in a solution called [Feedex](http://feedex.net/). A related blog article is [here](https://onetapless.com/expanding-truncated-rss-feeds).

**Comment by Minoru** [comment]
I'd have to say "no" to this request, sorry. The burden of detecting if the link is really a "continue" link or something else is just too high, and I'm not sure it's wise to make user's RSS reader go places just because feed's author decided to post a link.
