### ISSUE TITLE
Dynamically find out maximum allowed path length

### ISSUE THREAD

**Issue by Minoru** [akrennmair/newsbeuter#212]
While reading through the code, I found that you arbitrarily define the length of strings that hold paths, like in [`controller.cpp:1321`](https://github.com/akrennmair/newsbeuter/blob/master/src/controller.cpp#L1321). That **might** lead to problems. [ServerFault suggests](https://serverfault.com/questions/9546/filename-length-limits-on-linux/659950#659950) to always use `pathconf(3)`.

I'm pursuing different goals at the moment, thus an issue and not a patch. Sorry.

**Comment by akrennmair** [comment]
Using `pathconf(3)` is overkill because it can fail. The macro `_POSIX_PATH_MAX` is sufficient, and in that particular case, an even shorter buffer size could have been used, because the length of the resulting string is known in advance. In any case, this is fixed now.

**Comment by Minoru** [comment]
> Using `pathconf(3)` is overkill because it can fail. The macro
> `_POSIX_PATH_MAX` is sufficient

No; as link referenced from ServerFault states, it's important to use
`pathconf(3)` instead of macros cause the code might be run on a machine
with limits different from those on the build machine. So while this
issue is certainly not top- (or even normal-) priority, I'd say this
needs to be done.

I'll do it myself later, just as an excuse to look through the code if
nothing else.

> in that particular case, an even shorter buffer size could have been
> used, because the length of the resulting string is known in advance.

True, but see below.

> In any case, this is fixed now.

I meant this issue not as actual issue with particular code—the line
I mentioned was just an example—but as a reminder for me (or someone
else) to look through the code for places where this might be a problem.

So I'll be grateful if you re-open this issue, so that it can serve its
reminding purpose. I can even promise you to ping you in two weeks
regarding that; if I don't get this going by then, you'll just close it
again. Deal?

**Comment by akrennmair** [comment]
> No; as link referenced from ServerFault states, it's important to use
`pathconf(3)` instead of macros cause the code might be run on a machine
with limits different from those on the build machine. So while this
issue is certainly not top- (or even normal-) priority, I'd say this
needs to be done.

That's just not true. The glibc implementation of `pathconf(3)` just returns PATH_MAX. The FreeBSD implementation is a bit more complicated to follow because it actually goes into kernel space, but seems to simply return PATH_MAX for most (if not all) cases.

> So I'll be grateful if you re-open this issue, so that it can serve its
reminding purpose.

Fine with me.

**Comment by Minoru** [comment]
After reading through various bits and pieces on the Internet, most notably [a similar discussion in PostgreSQL's mailing list](http://www.postgresql.org/message-id/738.940654002@sss.pgh.pa.us), I'm not so sure of anything anymore T_T Decided to let it rest for now, until I either wise up and find The Right Way To Do It, or someone bumps into a related bug.

Thanks for your patience, @akrennmair.
