### ISSUE TITLE
highlight-article not working with unread article titles

### ISSUE THREAD

**Issue by mvucBmM0** [akrennmair/newsbeuter#227]
highlight-article isn't working with unread article titles. Colors stay unaltered.
It does however work properly with read articles.

**Comment by Minoru** [comment]
Confirmed; moreover, it seems like on first run after adding the `highligh-article` line to config, the articles that should be highlighted are absent from item list altogether.

**Comment by mvucBmM0** [comment]
Thanks for fixing that up.
