### ISSUE TITLE
Feature request: Have 'keep-articles-days' never delete unread articles

### ISSUE THREAD

**Issue by mvucBmM0** [akrennmair/newsbeuter#228]
In order to keep my feed cache as small as possible, i would like to be able to use the 'keep-articles-days 30' option but it unfortunately will also delete unread articles.
My request is to have an option to have newsbeuter never delete unread articles.
The 'delete-read-articles-on-quit' option is not an alternative either, cause then newsbeuter will just keep downloading the same articles over and over again (if they are recent enough obviously).

**Comment by Minoru** [comment]
Request accepted; I'll work on this once I get rid of backlog of bugs.

> The 'delete-read-articles-on-quit' option is not an alternative either, cause then newsbeuter will just keep downloading the same articles over and over again (if they are recent enough obviously).

Sounds like a bug. Split into #229.

**Comment by mvucBmM0** [comment]
Thank you. Looking forward for it.

**Comment by Minoru** [comment]
This is actually a duplicate of #103, so I'm closing this issue in favor of the older one.
