### ISSUE TITLE
Mark as read on open

### ISSUE THREAD

**Issue by deshtop** [akrennmair/newsbeuter#231]
I'd like to request a feature: By pressing ``o`` in the article list (so by opening the article in the browser), the respective article should be marked as read.
One may name this ``mark-as-read-on-open`` in analogy to the similar ``mark-as-read-on-hover``.
Thanks

**Comment by Minoru** [comment]
This is already present in the form of `open-in-browser-and-mark-read` command, which is bound to `O` by default. You can bind it to `o` as well, so as to avoid pressing Shift all the time:

```
bind-key o open-in-browser-and-mark-read
```
