### ISSUE TITLE
"A": mark all articles read: working, but not displayed, while in the feed

### ISSUE THREAD

**Issue by klartext** [akrennmair/newsbeuter#243]
When marking all articles/items as read with "A", while in the feed,
it looks like if this does not work.
When "q"uitting this view (and go up into the feed-list/-overview), then the the feed
is handled correctly, and all artikels are makred as read.
But this is not showed, as long one is inside the feed (in the article/items-view).

This is a regression, beacuse in newsbeuter 2.9 it was working correctly.
Ctrl-L does not redraw this.
(But  when entering/reading an article and going back to the feed/article-overview, then it's displayed correctly: all articles marked read then.)

**Comment by Minoru** [comment]
Hmm… I must've broken it during recent refactoring while trying to speed 
up massive deletions. Thanks for reporting, I'll look into this in the 
next few days.

**Comment by Minoru** [comment]
@pickfire also [reports](https://github.com/akrennmair/newsbeuter/commit/60a68ff48874c02ef569a8fd2ab5c258b58f6939#commitcomment-15397285):
>It seems like the last few latest commit had broke the command 'A' which is mark all feed read, probably this commit or the previous commit.
>
> When I pressed 'A', only the feed that is highlighted (the line I am on) is mark as read, the rest isn't marked as read.

**Comment by pickfire** [comment]
@Minoru, is there a test for the 'A' command, some rare commands that you seldom used might be a common command to someone. I think it is better if there is a script to test the commands.

**Comment by Minoru** [comment]
One part of tests are out of sync, the other I can't run yet because I didn't figure out how to use Ruby stuff. See #219. You're welcome to help, of course.

**Comment by pickfire** [comment]
I don't know ruby stuff too. Sorry :)

**Comment by sappel34** [comment]
Can be fixed easily in itemlist_formaction.cpp, line 328:
`old: invalidate(itempos);`
`new: invalidate(InvalidationMode::COMPLETE);`

**Comment by Minoru** [comment]
Thanks, @sappel34!
