### ISSUE TITLE
Fails to read configs from ~/.config/newsbeuter

### ISSUE THREAD

**Issue by Minoru** [akrennmair/newsbeuter#244]
From #107:
> I can confirm that it does indeed not work if you put the config files in ~/.config/newsbeuter.

**Comment by Minoru** [comment]
@mvucBmM0, writing that under #107 was wrong because that issue is about `~/.config/newsbeuter` not being the default.

But thank you for reporting the issue nonetheless. I can't reproduce it with current HEAD, though. I did the following:
```$ mv ~/.newsbeuter ~/.config/newsbeuter```

Then I started Newsbeuter, and it worked just fine. Can you provide steps to reproduce the issue, or maybe an explanation of "does not work" in case I'm misunderstanding you?

**Comment by mvucBmM0** [comment]
Sorry for the mistake, I thought it was directly related to the previous comments.
Anyway.

If i do:
$ mv ~/.newsbeuter ~/.config/newsbeuter

it outputs:

XDG: data directory '/home/me/.local/share/newsbeuter' not accessible, using '/home/me/.newsbeuter' instead.
Starting newsbeuter 2.10...
Loading configuration...done.
Opening cache...done.
Loading URLs from /home/me/.newsbeuter/urls...done.
Error: no URLs configured. Please fill the file /home/me/.newsbeuter/urls with RSS feed URLs or import an OPML file.

**Comment by mvucBmM0** [comment]
Ah, so it seems you have to remove the cache and history files from ~/.config/newsbeuter and place them in ~/.local/share/newsbeuter.
Then it works.
Guess you can close this threat, and sorry again.

**Comment by Minoru** [comment]
Oh, I got it! I have `XDG_DATA_HOME` set to `$HOME/.config`, so when 
I moved stuff into `~/.config/newsbeuter`, all of Newsbeuter's 
requirements were satisfied.

Okay, so quoting the Newsbeuter manual:

> Newsbeuter implements limited support for the XDG Base Directory 
> Specification. It needs to be set up manually by creating the 
> following directories:
>
>	~/.local/share/newsbeuter/
>	~/.config/newsbeuter/
>
> If these directories exist or the environment variables 
> $XDG_CONFIG_HOME and $XDG_DATA_HOME are set, newsbeuter will use these 
> directories, otherwise it will default to ~/.newsbeuter as its 
> configuration directory.

Thus, you need to move your config and urls file into 
`~/.config/newsbeuter` and your cache and history files into 
`~/.local/share/newsbeuter`—then you'll be set.

**Comment by Minoru** [comment]
You beat me to it :) Glad that isn't a bug, though. Keep flying 
Newsbeuter!

**Comment by pickfire** [comment]
>  If these directories exist or the environment variables
 $XDG_CONFIG_HOME and $XDG_DATA_HOME are set, newsbeuter will use these
 directories, otherwise it will default to ~/.newsbeuter as its
 configuration directory.

Shouldn't it redirect to ~/.config/newsbeuter if $XDG_CONFIG_HOME isn't set?

**Comment by Minoru** [comment]
[It does](https://github.com/akrennmair/newsbeuter/blob/ebd7bde2b0c18a94ee87e20228ded7627dbbfe2c/src/controller.cpp#L105-L107), @pickfire.

**Comment by pickfire** [comment]
@Minoru, it works after I manually move `~/.newsbeuter` which contains cache to `~/.local/share/` or it will show:
```
XDG: data directory '/home/ivan/.local/share/newsbeuter' not accessible, using '/home/ivan/.newsbeuter' instead.
Starting newsbeuter 2.10...
Loading configuration...done.
Opening cache...done.
Loading URLs from /home/ivan/.newsbeuter/urls...done.
Error: no URLs configured. Please fill the file /home/ivan/.newsbeuter/urls with RSS feed URLs or import an OPML file.

newsbeuter 2.10
usage: newsbeuter [-i <file>|-e] [-u <urlfile>] [-c <cachefile>] [-x <command> ...] [-h]
        -e, --export-to-opml            export OPML feed to stdout
        -r, --refresh-on-start          refresh feeds on start
        -i, --import-from-opml=<file>   import OPML file
        -u, --url-file=<urlfile>        read RSS feed URLs from <urlfile>
        -c, --cache-file=<cachefile>    use <cachefile> as cache file
        -C, --config-file=<configfile>  read configuration from <configfile>
        -X, --vacuum                    clean up cache thoroughly
        -x, --execute=<command>...      execute list of commands
        -o, --offline-mode              activate offline mode (only applies to The Old Reader synchronization mode)
        -q, --quiet                     quiet startup
        -v, --version                   get version information
        -l, --log-level=<loglevel>      write a log with a certain loglevel (valid values: 1 to 6)
        -d, --log-file=<logfile>        use <logfile> as output log file
        -E, --export-to-file=<file>     export list of read articles to <file>
        -I, --import-from-file=<file>   import list of read articles from <file>
        -h, --help                      this help
```

**Comment by Minoru** [comment]
@pickfire, `~/.newsbeuter` is the default. If you want XDG, you should set both environment variables or create both directories, as described in documentation. What exactly is wrong, in your opinion?

**Comment by pickfire** [comment]
@Minoru, I mean that I need move `~/.newsbeuter` to `~/.local/share/` **manually.

**That should be done by newsbeuter.**

### Note: I had already moved the configuration to `~/.config/newsbeuter`

**Comment by Minoru** [comment]
So you're telling me you've moved *some* of the files and now want Newsbeuter to figure out what you're doing and finish the job.

It's not Newsbeuter's job. You put files wherever you want, then tell Newsbeuter to look for them there. That's it.

**Comment by mvucBmM0** [comment]
I think what he means is this.
If you put your config and urls files in .newsbeuter, it will automatically create the cache and history files in that folder.
But if you put the config and urls files in .config/newsbeuter, it won't create them in local/share/newsbeuter.

**Comment by Minoru** [comment]
Oh! Yep, that makes sense. Will do.

**Comment by pickfire** [comment]
@mvucBmM0 Thanks for understanding what I mean.
