### ISSUE TITLE
feedlist multiple highlight colors

### ISSUE THREAD

**Issue by spcmd** [akrennmair/newsbeuter#247]
I'd like to highlight multiple keywords in the feedlist, but i'd like to use different colors for them, for example:
```
highlight feedlist "Youtube" white red
highlight feedlist "Arch" white blue
```
But it doesn't work. Is it possible to define different highlight colors for different keywords in the feedlist?

**Comment by Minoru** [comment]
This works in HEAD; please wait for 2.10 to be released.
