### ISSUE TITLE
Sorting Article feeds

### ISSUE THREAD

**Issue by Spreadcat** [akrennmair/newsbeuter#253]
Hi,

I saw the parameter *article-sort-order*, but I am missing the one for the article feeds. Is it possible to order those as well, e.g. alphabetically?

regards,
d.

**Comment by Minoru** [comment]
Um, what are "article feeds"?

**Comment by Spreadcat** [comment]
I guess I used the wrong terminology. I mean the list of configured feeds that opens right after starting Newsbeuter.The listing seems to depend on the order it is configured in in `~/.newsbeuter/url`. I am not sure why I came up with the termn "article-feeds".

**Comment by Minoru** [comment]
Oh, that's simply the feed list.

Use `feed-sort-order` setting for that. Acceptable values are `firsttag`, `title`, `articlecount`, `unreadarticlecount` and `none` (this one's the default). You can also select any of those on the fly if you press `g` while in the feedlist.

Hope this helps.

**Comment by Spreadcat** [comment]
Yes, that was what I was looking for. Thank you.

**Comment by Spreadcat** [comment]
Just a note: this parameter seems to be missing in the documentation. I would fork and send a pull-request, but I am not sure that I can cover all of its functionality.

**Comment by Minoru** [comment]
What documentation are you referring to? I can see the parameter mentioned both in [Newsbeuter manual](http://newsbeuter.org/doc/newsbeuter.html) (see Table 1 in Section 3) and newsbeuter's manpage. If you're looking at the source code in the repo, the parameter is actually described in `doc/configcommands.dsv`; the file is then processed and inserted in HTML and manpage. It's a bit involved, but guarantees that both documents are in sync, and also saves us some typing.

**Comment by Spreadcat** [comment]
ok.. you're right-. I suck at reading documentation:(
I promise to become better in looking for it ;)
Please forget that I complained.

**Comment by Minoru** [comment]
Oh, don't beat yourself about it! Instead, you can actually think what made you miss the parameter the first time you read the documentation and maybe suggest some readability improvements. Is it the structure of the doc that makes it hard? Maybe the parameter is named or described in such a way that you can't easily find it with search? I'll gladly accept suggestions and patches.
