### ISSUE TITLE
The manual should mention that TT-RSS folders are displayed as tags

### ISSUE THREAD

**Issue by Minoru** [akrennmair/newsbeuter#255]
See [this comment](https://github.com/akrennmair/newsbeuter/issues/188#issuecomment-175466110) for details.

**Comment by The-Compiler** [comment]
To elaborate: I've used newsbeuter before switching to ttrss, but didn't have many feeds, so I never needed tags.

Then I got more and more feeds with ttrss, so I named them like `category - feedname` so they are sorted properly in newsbeuter, as I didn't know the concept of tags (or sorting by tags) at all.
