### ISSUE TITLE
text starts off screen in news items

### ISSUE THREAD

**Issue by hidroto** [akrennmair/newsbeuter#256]
text does not start at the left of the page but off screen
this only just started to happen

i ran git bisect to find when it changed and came up with 26e47fc
below are screenshots of the issue

the first screenshot is from 26e47fc which is broken
the second is from 2efb75a93 an is okay
https://imgur.com/a/DBn4U

**Comment by Minoru** [comment]
I received a patch from Michael Krylov:

```
From 2b36d6237789db14587606850b017bb23df736b7 Mon Sep 17 00:00:00 2001
From: Michael Krylov <sqarert@gmail.com>
Date: Wed, 13 Apr 2016 14:45:25 +0300
Subject: [PATCH] Fix losing line contents if it is too long

---
 src/listformatter.cpp | 3 +++
 1 file changed, 3 insertions(+)

diff --git a/src/listformatter.cpp b/src/listformatter.cpp
index 60cc0ee..4bfc1d6 100644
--- a/src/listformatter.cpp
+++ b/src/listformatter.cpp
@@ -34,6 +34,9 @@ void listformatter::set_line(const unsigned int itempos,
 			}
 			line = line_id_pair(utils::wstr2str(mytext.substr(0, size)), id);
 			mytext.erase(0, size);
+			if (mytext.length() > 0){
+				lines.push_back(line);
+			}
 		}
 	} else {
 		line = line_id_pair(utils::wstr2str(utils::clean_nonprintable_characters(utils::str2wstr(text))), id);
```

It remedies a problem by splitting overly long lines, but the problem is somewhere higher the call stack—ideally, Newsbeuter should notice how wide the screen is and reformat the text accordingly.

**Comment by hidroto** [comment]
this does fix my issue.

> it remedies a problem by splitting overly long lines, but the problem is somewhere higher the call stack—ideally, Newsbeuter should notice how wide the screen is and reformat the text accordingly.

so this can not be a pull request?

**Comment by Minoru** [comment]
> so this can not be a pull request?

No, because I want a proper fix.

**Comment by Minoru** [comment]
@hidroto, can you build from bugfix/wrapfix branch and verify if the bug is fixed? (I could never reproduce it myself.)

**Comment by Minoru** [comment]
Actually, I just managed to reproduce it, and it looks like indeed it's fixed. Merging the fix into master.
