### ISSUE TITLE
Strange behaviour in combination with GNU Screen - top bar cut off when looking at RSS feed post

### ISSUE THREAD

**Issue by kozross** [akrennmair/newsbeuter#273]
I followed [these instructions][1] to get the ability to connect to Newsbeuter remotely using GNU Screen. Everything seemed ok, until I realized that the top bar (saying 'newsbeuter 2.9 - Your feeds' etc) was missing. Resizing my client terminal fixed this - until I tried to read a post on one of my feeds, when it promptly disappeared again. If I'm reading a post, resizing is of no help at all - and given that this cuts off the first few lines, it makes it rather difficult to read anything.

Is this a Screen issue, or is there something I can configure in Newsbeuter to make this not happen?

[1]: https://www.linux.com/learn/tutorials/442418-using-screen-for-remote-interaction

**Comment by Minoru** [comment]
No idea. I just checked with screen 4.02.01 and newsbeuter 2.9 and HEAD — it works for me.

I assume you're using 2.9?

What is the version of Screen?

Can you show your configs (both for Screen and Newsbeuter)?

And just as a guess — what does `echo $TERM` say inside and outside Screen?

**Comment by kozross** [comment]
It seems like I had misunderstood what I needed to do - that link describes screen *sharing*, while what I wanted was remote terminal work. After following a different set of suggestions, I no longer get this problem. Sorry for the confusion and the time-wasting.
