### ISSUE TITLE
Incorrect translation format

### ISSUE THREAD

**Issue by ghost** [akrennmair/newsbeuter#274]
i18nspector reveals a few issues with the current translation files, some missing arguments and an argument type mismatch which could possibly lead to crashes.

```
E: po/uk.po: c-format-string-missing-arguments msgid "`%s' is not a valid regular expression: %s": 1 (msgstr) < 2 (msgid)
E: po/zh.po: c-format-string-argument-type-mismatch msgid "Error while processing command `%s' (%s line %u): %s": int * (msgstr) != unsigned int (msgid)
E: po/zh.po: c-format-string-missing-arguments msgid "Error: couldn't mark feed read: %s": 0 (msgstr) < 1 (msgid)
```

There is also a warning that should probably be looked at:
`W: pt_BR.po: language-disparity pt_BR (pathname) != ru (Language header field)`
pt_BR is the Portuguese translation file, yet the language header is set to Russian.

**Comment by Minoru** [comment]
Thanks for reporting this!

I've fixed Ukrainian translation (happen to be a native speaker) and also Brazilian Portuguese.

I don't know Chinese, so that would have to wait until someone else fixes it. (I've asked on our IRC channel, hopefully we'll find someone.)

**Comment by Minoru** [comment]
There's nothing I can do to make Chinese translation improve, so I'm dropping the milestone on this one—it'll be done when someone steps up to do it.

**Comment by Minoru** [comment]
A prod from @tsipinakis made me realise I can edit those without any knowledge of Chinese. Yay!

No substitute for a knowledgeable person, though.
