### ISSUE TITLE
Slowness with mark-as-read-on-hover and no redraw on next

### ISSUE THREAD

**Issue by Earnestly** [akrennmair/newsbeuter#276]
I've for awhile now I've had `mark-as-read-on-hover yes` configured but it makes `n` key operations very slow, very easily noticable if `n` is held down and keyrepeat occurs. Sometimes it completely lock up and spontaneously complete all the `n`'s as if they were queued.

But more unfortunately for awhile now (I should have reported this earlier, sorry about that) when `n` takes you to the next feed it doesn't redraw the new feeds items except for the one you currently have selected.  This means all the previous' feeds are visible until you scroll around with `J` and `K` to "reveal" the real entries hidden behind the old feed's listing. Redrawing with `^L` doesn't have any effect although some quitting out of the feed and going back in does correct it (or invoking some macro that launches a program).

Was this intentional?  Is there a configuration to prevent this behaviour if so?

**Comment by Minoru** [comment]
Definitely *not* the intended behaviour.

Did you try b3605ac4d968fec96e27bd2fa71764c043d6a9a8 (pushed just three days ago)? I didn't check yet, but it might have fixed the problem with redrawing for you, too.

I'll have to profile to figure out why `n` is slow when `mark-as-read-on-hover` is set.

**Comment by Earnestly** [comment]
Are you able to replicate the behaviour of contents not being redrawn when `n` takes you to a new feed?

**Comment by Minoru** [comment]
Yes. Moreover, I got a segfault when I reached the end of the next feed.

I can't look into it just now. I'll write back once I do.

**Comment by Minoru** [comment]
Ouch, I ended up not looking at this one for a whole three months! Sorry. But I'm forced to move this to 2.11 milestone to unblock 2.10 release.

**Comment by Earnestly** [comment]
That's perfectly fine, no worries

**Comment by Earnestly** [comment]
The redraw issue seems to have been solved with recent commits (between https://github.com/akrennmair/newsbeuter/commit/30882c1cfd69e09d9d0ec66ae39a5f8fc95b42e8 and https://github.com/akrennmair/newsbeuter/commit/30882c1cfd69e09d9d0ec66ae39a5f8fc95b42e8).

I'm tentatively closing this for now as both issues no longer seems to be present with my limited testing.

Thanks o/

**Comment by Minoru** [comment]
I guess it's dc88c70c60b04155cbf88137acca13735c8a03af that fixed it. Be sure to re-open if the problem turn out to still be present after all.
