### ISSUE TITLE
All feeds empty

### ISSUE THREAD

**Issue by Earnestly** [akrennmair/newsbeuter#283]
* sqlite 3.12.1
* curl 7.48.0
* gcc 5.3.0

I updated newsbeuter to https://github.com/akrennmair/newsbeuter/commit/ffc376b13f10e92721cda7ab17cdbd2966f7e251 and have found that every feed is now `(0/0)`.

I've tried moving my history, cache and database away and it's still unable to fetch any new feeds.

I haven't had the time/chance to do any bisecting.

**Comment by Minoru** [comment]
Sorry about that!

**Comment by Earnestly** [comment]
No problem, this is why I run development versions of things :-P
