### ISSUE TITLE
Feed lists as empty in newsbeuter

### ISSUE THREAD

**Issue by kozross** [akrennmair/newsbeuter#288]
The feed in question is [here][1]. Obviously, from looking at it in a browser, it's *not* empty, but when I put it in my ``urls`` file, it says that it is.

[1]: http://matt-welsh.blogspot.com/feeds/posts/default

**Comment by Minoru** [comment]
You sure it's not your configuration or something? I wasn't able to reproduce neither with `r2.9` nor with `HEAD`—both show the same articles as my Firefox shows.

**Comment by kozross** [comment]
Never mind - seems a reload was all that I needed. Sorry about that.

**Comment by Minoru** [comment]
It's okay ;)
