### ISSUE TITLE
Re-enable TestNewsbeuterReload

### ISSUE THREAD

**Issue by Minoru** [akrennmair/newsbeuter#296]
While fixing #219 I had to disable one set of tests because they depend on testbed.newsbeuter.org, which is no longer functional.

The code can be found in [this blob](https://github.com/akrennmair/newsbeuter/blob/7d7f3374304453b0cb986cc0d14b3dca34c1a5a0/test/test.cpp#L36-L77), but the data that the host used to serve can't be found in the repo.

Eventually, there tests should be re-enabled.

**Comment by akrennmair** [comment]
Oops, I didn't realize I broke testbed.newsbeuter.org until I seen this issue here. That must have been when I switched from lighttpd to nginx a few months ago. Anyway, it's restored again.

**Comment by Minoru** [comment]
Oh, cool! Thanks.

**Comment by Minoru** [comment]
I realised that we can use `file://` schema instead of `http://`, which has the following benefits:

* Shouldn't affect coverage—we delegate dealing with this stuff to CURL.
* Tests aren't blocking on (potentially slow) Internet connection, and can even be run offline.

So you can take testbed offline for good.
