### ISSUE TITLE
OSX Lion: sudo command needed to run newsbeuter

### ISSUE THREAD

**Issue by visualisierte** [akrennmair/newsbeuter#32]
OSX 10.7.4: Newsbeuter need sudo command to run. Without sudo, i get the following error message "setlocale failed: No such file or directory ". I´ve installed newsbeuter with brew using this formula: https://github.com/posativ/homebrew-newsbeuter/blob/master/Formula/newsbeuter.rb

**Comment by danielcotton** [comment]
This can be closed. The formula for newsbeuter in Homebrew does not require invocation with sudo.
