### ISSUE TITLE
Simplest way to browse local bookmarks feed in newsbeuter?

### ISSUE THREAD

**Issue by diskotechjam** [akrennmair/newsbeuter#320]
I am looking for a bookmark script capable of adding urls to a local xml file which I could then add and browse in newsbeuter. I've looked into xmlstarlet a little bit, but I'm not sure if that's really the best choice for what I need. I was wondering if anyone had a simple way of doing this or if I am over-complicating the issue and there is an easier way to achieve the same results (ie browsing bookmarked articles in newsbeuter).

**Comment by Minoru** [comment]
This is not relevant to Newsbeuter, so I'm going to close the issue. Your workflow will be the same with any RSS reader out there: you'll have to generate a feed with your bookmarks and then subscribe to it with the reader.

If by "adding URLs" you mean not just pointing to some other site but copying the contents of that URL, then it gets quite complicated: you'll have to extract the content (i.e. strip away all the design clutter), which is not an easy task (but Readability.com does that somehow).

I'm not entirely sure, but social bookmarking sites might provide a feed of the articles you've bookmarked. Maybe look there?

**Comment by diskotechjam** [comment]
Hmmm.. What I am trying to do is figure out a way to set aside an article in newsbeuter so I can read it later. So when I'm randomly browsing my articles, i can set one aside to read later or mark it as special. After looking into it, I think maybe the best way to do it is to simply flag the article. with a character. 

Is it possible to create a query feed that contains all articles with a specific flag?

**Comment by Minoru** [comment]
Oh, sorry, I thought you wanted to generate an XML file *outside* of Newsbeuter.

Yes, your use-case is perfect fit for flags.

> Is it possible to create a query feed that contains all articles with a specific flag?

Yes. If you use "s" to mark your feeds, you can add the following to your urls file (untested):
````
"query:Starred articles:flags # \"s\""
````
