### ISSUE TITLE
Compile issue on 

### ISSUE THREAD

**Issue by skn** [akrennmair/newsbeuter#323]
% ./config.sh
Checking for package sqlite3... found
Checking for package libcurl... found
Checking for package libxml-2.0... found
Checking for package stfl... found
Checking for package json... found
Checking for package ncursesw... found
Checking for package libcrypto... found

Pulling the latest and trying `make` throws out this error

g++ -std=c++11 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/local/share/locale\"   -I/usr/include/libxml2    -I/usr/include/json-c   -I/usr/include/ncursesw    -DHAVE_OPENSSL=1 -o src/listformatter.o -c
src/listformatter.cpp
src/listformatter.cpp: In member function ‘void newsbeuter::listformatter::set_line(unsigned int, const string&, unsigned int, unsigned int)’:
src/listformatter.cpp:51:26: error: no matching function for call to ‘std::vector<std::pair<std::basic_string<char>, unsigned int> >::insert(std::vector<std::pair<std::basic_string<char>, unsigned int> >::const_iterator, std::vector<std::pair<std::basi
c_string<char>, unsigned int> >::const_iterator, std::vector<std::pair<std::basic_string<char>, unsigned int> >::const_iterator)’
     formatted_text.cend());
                          ^
src/listformatter.cpp:51:26: note: candidates are:
In file included from /usr/include/c++/4.8/vector:69:0,
                 from include/listformatter.h:5,
                 from src/listformatter.cpp:1:
/usr/include/c++/4.8/bits/vector.tcc:107:5: note: std::vector<_Tp, _Alloc>::iterator std::vector<_Tp, _Alloc>::insert(std::vector<_Tp, _Alloc>::iterator, const value_type&) [with _Tp = std::pair<std::basic_string<char>, unsigned int>; _Alloc = std::all
ocator<std::pair<std::basic_string<char>, unsigned int> >; std::vector<_Tp, _Alloc>::iterator = __gnu_cxx::__normal_iterator<std::pair<std::basic_string<char>, unsigned int>*, std::vector<std::pair<std::basic_string<char>, unsigned int> > >; typename s
td::_Vector_base<_Tp, _Alloc>::pointer = std::pair<std::basic_string<char>, unsigned int>*; std::vector<_Tp, _Alloc>::value_type = std::pair<std::basic_string<char>, unsigned int>]
     vector<_Tp, _Alloc>::
     ^
/usr/include/c++/4.8/bits/vector.tcc:107:5: note:   candidate expects 2 arguments, 3 provided
In file included from /usr/include/c++/4.8/vector:64:0,
                 from include/listformatter.h:5,
                 from src/listformatter.cpp:1:
/usr/include/c++/4.8/bits/stl_vector.h:988:7: note: std::vector<_Tp, _Alloc>::iterator std::vector<_Tp, _Alloc>::insert(std::vector<_Tp, _Alloc>::iterator, std::vector<_Tp, _Alloc>::value_type&&) [with _Tp = std::pair<std::basic_string<char>, unsigned
int>; _Alloc = std::allocator<std::pair<std::basic_string<char>, unsigned int> >; std::vector<_Tp, _Alloc>::iterator = __gnu_cxx::__normal_iterator<std::pair<std::basic_string<char>, unsigned int>*, std::vector<std::pair<std::basic_string<char>, unsigned int> > >; typename std::_Vector_base<_Tp, _Alloc>::pointer = std::pair<std::basic_string<char>, unsigned int>*; std::vector<_Tp, _Alloc>::value_type = std::pair<std::basic_string<char>, unsigned int>]
       insert(iterator __position, value_type&& __x)
       ^
/usr/include/c++/4.8/bits/stl_vector.h:988:7: note:   candidate expects 2 arguments, 3 provided
/usr/include/c++/4.8/bits/stl_vector.h:1005:7: note: void std::vector<_Tp, _Alloc>::insert(std::vector<_Tp, _Alloc>::iterator, std::initializer_list<_Tp>) [with _Tp = std::pair<std::basic_string<char>, unsigned int>; _Alloc = std::allocator<std::pair<s
td::basic_string<char>, unsigned int> >; std::vector<_Tp, _Alloc>::iterator = __gnu_cxx::__normal_iterator<std::pair<std::basic_string<char>, unsigned int>*, std::vector<std::pair<std::basic_string<char>, unsigned int> > >; typename std::_Vector_base<_Tp, _Alloc>::pointer = std::pair<std::basic_string<char>, unsigned int>*]
       insert(iterator __position, initializer_list<value_type> __l)
       ^
/usr/include/c++/4.8/bits/stl_vector.h:1005:7: note:   candidate expects 2 arguments, 3 provided
/usr/include/c++/4.8/bits/stl_vector.h:1023:7: note: void std::vector<_Tp, _Alloc>::insert(std::vector<_Tp, _Alloc>::iterator, std::vector<_Tp, _Alloc>::size_type, const value_type&) [with _Tp = std::pair<std::basic_string<char>, unsigned int>; _Alloc = std::allocator<std::pair<std::basic_string<char>, unsigned int> >; std::vector<_Tp, _Alloc>::iterator = __gnu_cxx::__normal_iterator<std::pair<std::basic_string<char>, unsigned int>*, std::vector<std::pair<std::basic_string<char>, unsigned int> > >; typename std::_Vector_base<_Tp, _Alloc>::pointer = std::pair<std::basic_string<char>, unsigned int>*; std::vector<_Tp, _Alloc>::size_type = unsigned int; std::vector<_Tp, _Alloc>::value_type = std::pair<std::basic_string<char>, unsigned int>]
       insert(iterator __position, size_type __n, const value_type& __x)
       ^
/usr/include/c++/4.8/bits/stl_vector.h:1023:7: note:   no known conversion for argument 1 from ‘std::vector<std::pair<std::basic_string<char>, unsigned int> >::const_iterator {aka __gnu_cxx::__normal_iterator<const std::pair<std::basic_string<char>, un
signed int>*, std::vector<std::pair<std::basic_string<char>, unsigned int> > >}’ to ‘std::vector<std::pair<std::basic_string<char>, unsigned int> >::iterator {aka __gnu_cxx::__normal_iterator<std::pair<std::basic_string<char>, unsigned int>*, std::vect
or<std::pair<std::basic_string<char>, unsigned int> > >}’
/usr/include/c++/4.8/bits/stl_vector.h:1044:9: note: template<class _InputIterator, class> void std::vector<_Tp, _Alloc>::insert(std::vector<_Tp, _Alloc>::iterator, _InputIterator, _InputIterator) [with _InputIterator = _InputIterator; <template-parameter-2-2> = <template-parameter-1-2>; _Tp = std::pair<std::basic_string<char>, unsigned int>; _Alloc = std::allocator<std::pair<std::basic_string<char>, unsigned int> >]
         insert(iterator __position, _InputIterator __first,
         ^
/usr/include/c++/4.8/bits/stl_vector.h:1044:9: note:   template argument deduction/substitution failed:
src/listformatter.cpp:51:26: note:   cannot convert ‘((newsbeuter::listformatter*)this)->newsbeuter::listformatter::lines.std::vector<_Tp, _Alloc>::cend<std::pair<std::basic_string<char>, unsigned int>, std::allocator<std::pair<std::basic_string<char>,
 unsigned int> > >()’ (type ‘std::vector<std::pair<std::basic_string<char>, unsigned int> >::const_iterator {aka __gnu_cxx::__normal_iterator<const std::pair<std::basic_string<char>, unsigned int>*, std::vector<std::pair<std::basic_string<char>, unsign
ed int> > >}’) to type ‘std::vector<std::pair<std::basic_string<char>, unsigned int> >::iterator {aka __gnu_cxx::__normal_iterator<std::pair<std::basic_string<char>, unsigned int>*, std::vector<std::pair<std::basic_string<char>, unsigned int> > >}’
     formatted_text.cend());
make: *** [src/listformatter.o] Error 1

**Comment by Minoru** [comment]
You need at least GCC 4.9 to build Newsbeuter as C++11 support in GCC 4.8 is incomplete. (Clang 3.6 and above work fine, too.)

Now that I look at README I see this isn't mentioned even though it's been true for quite some time. Will fix that, thanks for the prod!
