### ISSUE TITLE
Strange behaviour interpreting a macro

### ISSUE THREAD

**Issue by giacecco** [akrennmair/newsbeuter#334]
I have this macro defined at the bottom of my _config_ file.

```
macro L set browser "/usr/local/bin/t favorite `echo %u | sed -r 's/.*\/([0-9]+)$/\1/'`"; open-in-browser ; set browser "firefox"
```

(if you're curious, I read Twitter using newsbeuter and [wrote a script transforming Twitter searches and lists in Atom feeds](https://github.com/Digital-Contraptions-Imaginarium/twitter2rss); this macro uses [the _t_ command line Twitter client](https://github.com/sferik/t) to set a tweet as favourite)

When I start newsbeuter, tI get the following:

```
$ newsbeuter
Starting newsbeuter 2.10...
Loading configuration...sed: -e expression #1, char 17: unknown option to `s'
done.
(...)
```

I can't guess what that means, it looks like a _sed_ error. Perhaps newsbeuter is confused by the quotes in the macros and tries to execute the _sed_ command? Thank you in advance for any suggestion.

**Comment by Minoru** [comment]
Newsbeuter evaluates text between two backticks as a shell command, just like shell does. This is a feature.

But apparently there's no way to *escape* the backtick. That's a bug :)

You can put that whole command into a script and use that as your `browser` until the bug is fixed.

**Comment by Minoru** [comment]
If you can build from Git—I think you mentioned in one of the issues that you're running HEAD?—you can try `bugfix/334-escapable-backticks` branch; it should fix the issue.
