### ISSUE TITLE
Pass feed title to bookmark script?

### ISSUE THREAD

**Issue by diskotechjam** [akrennmair/newsbeuter#341]
I currently use wget in my bookmark script to download pages to a local folder

mkdir ~/.newsbeuter/bookmarks/"${description}"
wget ${url} -O ~/.newsbeuter/bookmarks/"${description}"/"${title}".html

However, this requires me to manually set a description. Is it possible to pass a feed title to a bookmark script or automatically fill description with a certain value? For example, 

mkdir ~/.newsbeuter/bookmarks/"${feedtitle}"
wget ${url} -O ~/.newsbeuter/bookmarks/"${description}"/"${feedtitle}".html

**Comment by Minoru** [comment]
Feed title is not passed down to the script at the moment. We can add that, though.

But I'm not sure how that should work with query feeds. What should the parameter contain if you're in an article list for a query feed? Should it be query feed's title, or the title of the feed where item comes from? Should item view behave differently?

**Comment by diskotechjam** [comment]
Based on my current use, simply passing the actual feed title would make the most sense. However, I really only use query feeds to browse articles I have marked for later reading and the bookmark script for archiving pages locally. I could definitely see a situation where having the query title would be useful for organization, but the description input already allows a fair amount of flexibility for changing how and where the files are saved, so it might not be as necessary on a daily basis.

**Comment by Minoru** [comment]
I'm sorry for the silence. Hoped to finish this yesterday, but URL view turned out to be trickier than the rest. I'm done with the coding now, but I haven't tested anything yet, and I'm out of steam for today. It compiles, though, so you can try it yourself (make a backup first!)—check out `feature/341-pass-feed-title-to-bmk-script` branch.

**Comment by Minoru** [comment]
I'm back. Don't bother compiling that branch—I forgot to pass the actual parameter to the script! But when I do, everything segfaults. I'm trying to figure out how I ended up breaking things so badly.

**Comment by Minoru** [comment]
Fixed, tested and merged into master. Should be released as part of 2.10.

It'd be cool if you could test it, too, and write back if you find anything doesn't work as expected.

**Comment by diskotechjam** [comment]
Just tried this out, works perfectly. thanks!
