### ISSUE TITLE
SQL-Command needed for completely deleting a feed and all it's items

### ISSUE THREAD

**Issue by klartext** [akrennmair/newsbeuter#343]
A while ago I opened a ticket because removing items was too slow.
That problem has been fixed at least a bit: deleting items became faster.
But for very big feeds (e.g. 10k items) it's still too slow.

If I want to drop a feed and all it's items completely, what command do I need to use in sqlite3,
to achieve that job?

(And maybe there could be a remove-command for completely removing the feed from the db?)

(If the feed is still in the urls-file, of course new reloading of the feed should create an entry again.)

**Comment by Minoru** [comment]
If you have `cleanup-on-quit` set to `yes` (which is the default value), Newsbeuter will do that for you: if you remove a feed from your urls file and close Newsbeuter, it will remove all of this feed's items from the cache. I think that obviates the need for sqlite3 command and/or separate Newsbeuter command.

**Comment by klartext** [comment]
Minour, thank you, that's great!
