### ISSUE TITLE
Hide cursor from feedlist and articlelist

### ISSUE THREAD

**Issue by sudo-nice** [akrennmair/newsbeuter#344]
![window-220706](https://cloud.githubusercontent.com/assets/1666518/17567452/762fd89e-5f50-11e6-8c8c-6c38a3af8fe2.png)
Do we really need the cursor (that red rectangle) in the main window (not command line)? Maybe, it worth to hide it, or add an option?

**Comment by Minoru** [comment]
I agree, that looks bad.

I actually wonder where the red is coming from—it's certainly not the default in Newsbeuter itself, and the theme you're using (solarized, right?) only uses red to highlight URLs in articles.

**Comment by sudo-nice** [comment]
Red color is intended by my urxvt's config. I only wanted to raise the question at all, regardless of the cursor's color.

**Comment by Minoru** [comment]
#379 and #384 implemented this change for Newsbeuter, but Podbeuter still displays the cursor. This, too, shall be fixed.
