### ISSUE TITLE
No feed items

### ISSUE THREAD

**Issue by kaihendry** [akrennmair/newsbeuter#349]
Why doesn't http://webconverger.org/blog/index.atom parse?

It's mostly valid compared to https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwebconverger.org%2Fblog%2Findex.atom

**Comment by tsipinakis** [comment]
![2016-08-30t10-07-17](https://cloud.githubusercontent.com/assets/18189112/18079463/8eadeae8-6e99-11e6-8af0-8de0050d46ef.png)

Its working fine here. Did you try a reload-all(R) or manual reload(select the feed and press r)?

**Comment by kaihendry** [comment]
Oh sorry, "r" made it work. Very odd!

**Comment by Minoru** [comment]
Can you describe your scenario in more detail? I'm curious if this is the same issue as #346.

**Comment by toke** [comment]
I had / have the same issue. I suspect it to be related to atom feeds but could not rule it out.

One of the Feeds that had the Issue is:
 * http://alternativlos.org/alternativlos.rss 
 * https://alternativlos.org/ogg.rss
 * https://alternativlos.org/opus.rss

**Comment by Minoru** [comment]
@toke, I just checked all three feeds and they work for me with HEAD.

Can you please:
* specify which version of Newsbeuter you're running;
* list the steps you perform;
* describe the expected and actual behaviour (be sure to mention any errors Newsbeuter displays).
