### ISSUE TITLE
Article index order

### ISSUE THREAD

**Issue by mvucBmM0** [akrennmair/newsbeuter#350]
Hi

I would like to know if it is possible to sort the articles in reverse chronological order (older on top) but with the article index in descending order.                                                                                                  

Example output would be something like:

"3" "Aug 31" "Article name"
"2" "Sep 01" "Article name"
"1" "Sep 02" "Article name"

currently it shows like so:

"251" "Aug 31" "Article name"
"252" "Sep 01" "Article name"
"253" "Sep 02" "Article name"

If not possible I would like to make it a feature request.
In my opinion it makes more sense and is more readable and easier to use (if you have it in that date order) because it makes it easier to see how many unread articles you have left.

**Comment by Minoru** [comment]
Hi,

It's not possible, no. Furthermore, I believe your argument for adding such a feature is flawed in two ways.

1. The exact number of unread articles is already displayed in the articlelist title  by default (see ["Format Strings" section](http://newsbeuter.org/doc/newsbeuter.html#_format_strings) in the doc.)
2. Change in indexing doesn't help if you mix read and unread items, or if you're at the end of the feed full of unread articles.

I believe using `%u` in the articlelist title will solve your problem.

**Comment by mvucBmM0** [comment]
I do have the unread number in the article title but I usually only mark them as read once I've eye browsed through the whole article list, and even if I did mark them as read one by one, you still have to lose concentration by finding it in the feed title. And the article index number as is, doesn't really do much in quickly telling you where you are.
For example.
I have feeds that fill with many articles very fast, so when I'm browsing through pages of them from up to down, would be nice to know where I am.
I guess what I was wishing for was the exact opposite of the "article-sort-order date-desc".
As for number 2, I usually go through articles from older to new, so I don't really have read articles in the middle of unread ones.

Not a big deal of course, I would just prefer to go up to down instead of the opposite (which is what I'm actually using because of this) as it would be faster to go through article titles and I could actually use the N keybind (not really usable if you use date-desc because it marks it as read and then goes one down, instead of one up).

**Comment by Minoru** [comment]
> you still have to lose concentration by finding it in the feed title

You can customize the title for the count to stand out. Put it at the very beginning, perhaps?

My issue with your request is that you have a problem and want a custom solution where you already have means to reconfigure Newsbeuter to behave near-perfectly.

Please, set `article-sort-order` to `date-asc`, change articlelist title for unread count to stand out, and use `N`.

**Comment by mvucBmM0** [comment]
I guess I'll stick with that. Thanks for your time.
