### ISSUE TITLE
Sorting should happen after query feeds are prepopulated

### ISSUE THREAD

**Issue by Minoru** [akrennmair/newsbeuter#362]
With the following config:
```
feed-sort-order unreadarticlecount-desc
prepopulate-query-feeds yes
```
the query feeds will always be at the bottom of the list. Apparently, at the time of sorting they aren't yet populated, and their unread count is 0.

**Comment by gpakosz** [comment]
Confirmed it works for me. Thanks for improving things so quickly. Appreciated!
