### ISSUE TITLE
Feature-Wish: batching-option just for updating cache.db

### ISSUE THREAD

**Issue by klartext** [akrennmair/newsbeuter#372]
I would like to have an option, where it is possible to start newsbeuter just to update the database, and then right after it, to end execution.

I would like to use that to update the database, without the need to interact with newsbeuter.
With "--refresh-on-start" it would need me to end newsbeuter by hand.
This is interactivity, which I want to avoid.

In case you don't know what that feature is needed for: I would like to update the database via cron-job, because some feeds only have small number of entries in the RSS-feed and update often, so that I would miss items, if I use newsbeuter not often enough.

**Comment by Minoru** [comment]
I believe `-x reload` does just that. See ["Commandline commands"](https://newsbeuter.org/doc/newsbeuter.html#_commandline_commands) section of the documentation.

**Comment by Minoru** [comment]
@klartext, did `-x reload` fit your needs?

**Comment by klartext** [comment]
I could not test them, when the errors with the newsbeuter-directories (~./newsbeuter vs. CPATH-stuff) were present. (I found them out that way, trying the reload-stuff).
After fixing them, I forgot the batching-issue. Good that you reminded me. :)

Just tested it.
Works fine now, so I can close the issue.
