### ISSUE TITLE
symbolic link from ~/.newsbeuter to ~/.config/newsbeuter => no feeds found

### ISSUE THREAD

**Issue by klartext** [akrennmair/newsbeuter#375]
I have my newsbeuter-stuff in ~/.newsbeuter/

When trying to use -x option, I found that there is no fallback to ~/.newsbeuter and the files are looked for in ~/.config/newsbeuter.
( See https://github.com/akrennmair/newsbeuter/issues/374 )

So I created a symbolic link from ~/.newsbeuter/  to ~/.config/newsbeuter

Then -x option could be used, but no feeds are there, when starting newsbeuter normally (without any options/switches on CLI).

**Comment by Minoru** [comment]
When XDG mode is used, `~/.config/newsbeuter` contains only `config` and `urls` files—the database goes to a data dir (`~/.local/share/newsbeuter/` by default). But in ordinary mode everything goes to `~/.newsbeuter`.

So if you create a symlink, Newsbeuter doesn't realise that it should switch into XDG mode, and thus fails to find the DB.

In your situation, the correct solution is to switch to XDG mode completely, i.e. copy files over XDG directories and then remove `~/.newsbeuter`.
