### ISSUE TITLE
Broken link to snownews script tutorial in docs

### ISSUE THREAD

**Issue by anlar** [akrennmair/newsbeuter#377]
From https://newsbeuter.org/doc/newsbeuter.html#_scripts_and_filters_snownews_extensions

> If you want to write your own extensions, refer to this website for further instructions: http://kiza.kcore.de/software/snownews/snowscripts/writing

Returns 404.

**Comment by Minoru** [comment]
Thanks for reporting this! I found [a copy](https://web.archive.org/web/20090724045314/http://kiza.kcore.de/software/snownews/snowscripts/writing) in Web Archive, but if the document haven't been updated in the last 7 years, I'm not sure how useful it is. Apparently you're looking into Snownews extensions now, so if you find a more useful guide, be sure to tell me about it!
