### ISSUE TITLE
newsbeuter hangs when encountering certain mailchimp feeds

### ISSUE THREAD

**Issue by justa9** [akrennmair/newsbeuter#385]
Hello.

newsbeuter seems to hang when encountering at least one mailchimp feed. 
Namely, when I'm trying to read (any) specific article in the feed(minus the spaces):

```
http: / /us3.campaign-archive1.com /feed?u=0acae22e2c6bab797a76e44f3 & id=903691d971
```
the app hangs and responds only to Ctrl+z (suspend) for the subsequent kill.

```
Version: newsbeuter 2.9

Compilation date/time: Apr 27 2016 22:22:54
System: Linux 4.8.0-22-generic (i686)
Compiler: g++ 5.3.1 20160424
ncurses: ncurses 6.0.20160625 (compiled with 6.0)
libcurl: libcurl/7.50.1 GnuTLS/3.5.3 zlib/1.2.8 libidn/1.33 librtmp/2.3 (compiled with 7.47.0)
SQLite: 3.14.1 (compiled with 3.11.0)
libxml2: compiled with 2.9.3
```

Any ideas?

**Comment by Minoru** [comment]
Thanks for a report! Apparently it's Facebook's share links that break things. The links are so long that Newsbeuter hangs trying to wrap them to fit onto the screen.

Anyway, this has been fixed in 885760cf, and will be released with Newsbeuter 2.10.
