### ISSUE TITLE
Automatic feed naming

### ISSUE THREAD

**Issue by AdrianSchurz** [akrennmair/newsbeuter#403]
Weell, there I am abusing the issue management. But I kind of hate email, possess no social media accounts and there is no github private messaging. Sue me (God no, pls don't).

I slapped together a little script to automatically name my rather long list of youtube subscriptions which I imported to newsbeuter and then decided to make it available instead of letting it just slowly succumb to data corruption on an aging hard drive.

The repo is the absolutely spectacularily wittily named [newsbeuter-ytchannel-autoname](github.com/AdrianSchurz/newsbeuter-ytchannel-autoname)

And I would like to leave it here in case someone searches the repo for "automatic" and or "naming".

Cya

**Comment by Minoru** [comment]
There, I think a more descriptive title will make it more searchable.

We actually have `contrib` directory where people can put stuff like that. I'll gladly accept a PR that includes your script in there.

**Comment by AdrianSchurz** [comment]
Oy, neato torpedo, I will eventually do that.
Unfortunately I need to sort things out first and make sure I did not work on a non-issue. I have installed newsbeuter on a second machine not yet changing any article or feed-formatting and all feed titles get inferred and displayed smoothly. I will need to trace what combination of query feeds and (perhaps malformed) formatting even led me to add these names via the urls file on the other box.

Laters

**Comment by AdrianSchurz** [comment]
Soo, for the moment I cannot reproduce the circumstances where the feed names are not displayed properly. Which points to a previously malformed config file on my part. Unless a similar issue pops up for someone else the usefulness of this script is severely limited. The only thing I can think of is the hypothetical case where someone wants to delete youtube subscriptions from the urls file (skimming the docs I have the impression that that is the only way to remove feeds?) and can't decide which one is the correct line to delete.

My proposal would be:
Let's not merge the script into contrib yet, I will put some work into it anyway since a weird infrequent error caught my eye while trying to issue the http requests in parallel and I want to use the opportunity to see if I can piece together a working shell script unit testing environment (a thing I wanted to do for a while now and just needed a good excuse).

I will issue a pull request eventually.

Cheerio

**Comment by Minoru** [comment]
> to delete youtube subscriptions from the urls file (skimming the docs I have the impression that that is the only way to remove feeds?)

Correct.

> The only thing I can think of is the hypothetical case where someone wants to delete youtube subscriptions from the urls file and can't decide which one is the correct line to delete.

Feed view displays the URL of the feed in the title, so it's pretty easy to match. #258 will simplify this even further.

> Let's not merge the script into contrib yet,

Okay.
