### ISSUE TITLE
itemlist_formaction test may pass when implementation is wrong

### ISSUE THREAD

**Issue by Minoru** [akrennmair/newsbeuter#409]
I described the issue in detail in [this comment](https://github.com/akrennmair/newsbeuter/pull/380#discussion_r85649264), but it wasn't addressed and I missed that.

**Comment by tkerdonc** [comment]
Wow, not sure what I was thinking when I modified that test but it indeed doesn't test much as is. Will fix this and 410 as soon as I get the time and submit a PR. Or would you rather have this done with the rest of the itemlist_formaction tests ?

**Comment by Minoru** [comment]
You can bundle this and #410 into one PR—one commit even—but keep the rest out of it (i.e. as a separate PR.)

Maybe leave a comment here (and in #410) when you start on it so we don't duplicate the work—I feel like I'll sweep through the tracker for a low-hanging fruit soon, and this issue is definitely one of those :)

**Comment by tkerdonc** [comment]
Submitting a fix in PR [411](https://github.com/akrennmair/newsbeuter/pull/411)
