### ISSUE TITLE
itemlist_formaction test imposes unnecessary restrictions on implementation

### ISSUE THREAD

**Issue by Minoru** [akrennmair/newsbeuter#410]
See [this comment](https://github.com/akrennmair/newsbeuter/pull/380#discussion_r85649324) for details.

**Comment by tkerdonc** [comment]
Submitting a fix in PR [https://github.com/akrennmair/newsbeuter/pull/411](411)

**Comment by Minoru** [comment]
Wait. This issue is invalid—you *did* address my remark about ordering and added both `unordered_set` and `INFO`. I'm closing this issue now; sorry for bothering you!
