### ISSUE TITLE
'show-read-articles no' hides articles on auto-reload

### ISSUE THREAD

**Issue by AndreiUlmeyda** [akrennmair/newsbeuter#412]
As briefly mentioned in #402, if:
- newsbeuter is configured to not show articles that are marked as read and
- newsbeuter is configured to auto reload and
- articles are displayed inside a query feed

then

- articles are not hidden as soon as they are marked as read
- they are hidden when an auto reload happens

That is an issue, because the docs do not, at the moment,  state clearly what the intended behaviour would be.

Potential resolutions:
1. Update all the docs.
2. Reach a consensus as to what the behaviour should be and implement + update docs.

My personal preference would be to hide articles immediately or after a short delay (5 seconds maybe) on marking them as read although that may be inconvenient in work flows different than mine, I do not really know.

**Comment by Minoru** [comment]
Tried this, it looks like query feeds behave consistently with the rest of feeds, which are updated either when you leave the dialog, when auto-reload happens, or when you press `purge-deleted` (`$`).

I'm not entirely sure how to document this. Mention this all over the docs? Create a new section explaining when dialogs are updated? It seems like over-explaining to me; aren't you just get used to it and grasp it intuitively after some time?

> hide articles immediately or after a short delay (5 seconds maybe)

You won't be able to un-delete articles or mark them unread if they disappear too quickly. OTOH auto-update that happens in the middle of your reading might prevent you from doing it, too. I'll have to meditate on that.

**Comment by AndreiUlmeyda** [comment]
> It seems like over-explaining to me
Well, probably. I've used newsbeuter for a while now to see which issues go away and this one mostly did. The last little thing that remains I will open another issue for.
