### ISSUE TITLE
Error: feeds contains no items! On roughly half of feeds

### ISSUE THREAD

**Issue by eyvindbjartiandersen** [akrennmair/newsbeuter#417]
Version: Newsbeuter 2.8 and Newsbeuter 2.9

This could be a simple mistake but I can't fix it.

http://feeds.feedburner.com/TheJavascriptPlayground is one feed that don't work.

**Comment by Minoru** [comment]
Have you just added those feeds? If yes, you should either wait for the next auto-reload, or just reload them manually (using either `R` or `r`.)

If this isn't it, I'll investigate further in 12 hours or so.

**Comment by eyvindbjartiandersen** [comment]
I've already tried reloading using R and r.

**Comment by eyvindbjartiandersen** [comment]
I'm using the packages from the Arch Linux AUR and the official 
repository.

**Comment by Minoru** [comment]
I checked this feed with both 2.8 and 2.9 (built from this repo) and both successfully downloaded the items.

Does Newsbeuter display any errors? When you select one of the feeds and press `r`, there should be a message at the bottom of the window saying "Loading https://example.com/feed.rss...", and then it will disappear and the feed will be full of items. Or it go from "Loading" to "Error while retireving".

**Comment by eyvindbjartiandersen** [comment]
It loads it just fine and sets the title of feed as usual but when I try 
to open it I get that error message.

**Comment by Minoru** [comment]
Did you delete all the items, either manually or through some settings (using "Catchup all" when `delete-read-articles-on-quit` is set)?

**Comment by eyvindbjartiandersen** [comment]
No. I've just checked.

**Comment by eyvindbjartiandersen** [comment]
Now I've found out that trying to add https://adambard.com/blog/feed.xml 
in Snownews I get a the following error: Error in server reply. But I 
tested the feed on feedly.com so that works but not in Newsbeuter. This 
is the problem that must be having with the feeds in Newsbeuter.

**Comment by eyvindbjartiandersen** [comment]
Using feedvalidator.org https://adambard.com/blog/feed.xml fails. But then I tested http://feeds.feedburner.com/dailyjs which passed with some minor problems, here is the result: http://www.feedvalidator.org/check.cgi?url=http%3A%2F%2Ffeeds.feedburner.com%2Fdailyjs

**Comment by Minoru** [comment]
I somehow messed up the `To` header in the reply written two days ago, so GitHub didn't display it. Here it is, as I still believe it's relevant:

> > No. I've just checked.
>
> How exactly did you check? Here's how I imagine it:
> 
> 1. You run `newsbeuter -c /tmp/cache.db` (given /tmp/cache.db doesn't 
>    exist; the point being to test things with a fresh DB). Edit: add
>    `-l6 -dnewsbeuter.log` too, and post the resulting newsbeuter.log.
> 
> 2. You press `R` to update your feeds.
> 
> 3. You check if the feeds were populated with items.
> 
> Did you do just that?

Now to new details you supplied:

> Is the error in Newsbeuter or in the feeds?.

Can't tell yet. The errors in the feeds don't look so grave, and indeed both feeds you mentioned work for me just fine.

Snownews' error might be the key, but I don't understand why Newsbeuter doesn't report the same error. Please post the log I mentioned above, maybe it'll give us an answer.

**Comment by eyvindbjartiandersen** [comment]
Newsbeuter was launched with the flags but the same error occurs. Error log: http://www.filedropper.com/newsbeuter

**Comment by Minoru** [comment]
> Newsbeuter was launched with the flags but the same error occurs.

No, you didn't specify `-c`:

> [2016-11-14 14:59:00] DEBUG: utils::try_fs_lock: trying to lock /home/decimo/.newsbeuter/cache.db.lock
> …
> [2016-11-14 14:59:00] DEBUG: running: query: SELECT lastmodified, etag FROM rss_feed WHERE rssurl = 'https://jvns.ca/atom.xml';
> [2016-11-14 14:59:00] INFO: lastmodified_callback: lastmodified = 1479005880 etag = "2ee43-54125e41a0545"

But: last item in DailyJS was posted on July 7th, 2015; last item in Adam Bard's feed was posted on November 4th, 2016; you have `keep-articles-days` set to 7. That's why our issue template explicitly mentions that settings are steps too.

Hope this resolves the issue?

**Comment by eyvindbjartiandersen** [comment]
That resolved the issue. I was unclear on how it worked. Thank you for 
clarifying and this amazing piece of software.

**Comment by Minoru** [comment]
Cool! If you have hints on how we can improve the documentation for `keep-articles-days` to make it easier to understand, please share! (Here or in the separate issue or maybe even a PR.)
