### ISSUE TITLE
podbeuter crash

### ISSUE THREAD

**Issue by Exapiper** [akrennmair/newsbeuter#418]
**Newsbeuter version**:
**newsbeuter-2.9-2.fc24.x86_64**

Podbeuter segmentation faults at certain times.

Steps to reproduce the issue:
1. Use Fedora 24
2. Install from repo
3. Add at least one url to the ~/.newsbeuter/urls file
4. Attempt to download a queued file using podbeuter

I did confirm this on a fresh install of Fedora 24 in a VM in addition to my own native desktop

**Other info you think is relevant**:

**Comment by tsipinakis** [comment]
Duplicate of #167, has already been fixed in HEAD.

**Comment by Exapiper** [comment]
Very well. My assumption is that means the ball is in the distro's court on building a more up to date rpm?

(I'm not versed in how that works)

Thankyou.

**Comment by Minoru** [comment]
> My assumption is that means the ball is in the distro's court on building a more up to date rpm?

Not necessarily. We didn't make a new release that includes this fix (having trouble with this, sorry), so it's not like they *must* build new RPM. On the other hand, they *can* notice that we fixed things but are lingering with the release, and decide to backport fixes and release a new RPM with version like 2.9-3.

**Comment by Exapiper** [comment]
Thanks for the explanation. I did happen to figure out the dependencies for installing the git version. 
Podbeuter doesn't crash now fortunately, but it doesn't succeed in downloading anything; it just says failed instantly once I press 'd'. 

Is the fix included in the git version?

**Comment by Minoru** [comment]
> I did happen to figure out the dependencies for installing the git version.

We have a list of dependencies in the README. Isn't it up to date? Did you have to install anything not mentioned there? I admit I might've missed something.

> it just says failed instantly once I press 'd'.

That's a separate issue. Split into #421. I don't have a fix yet.

**Comment by Exapiper** [comment]
The dependency list is good, it's fedora for some reason every one of the versions just required the "devel" package and once I got that figured it installed.

**Comment by Minoru** [comment]
Ah, I see. It's common practice to package libraries, their debug symbols and their development-related components into three different packages (in Debian that would be "X", "X-dbg" and "X-dev") so that ordinary users can save disk space on things they don't need.
