### ISSUE TITLE
master fails to build due to warnings

### ISSUE THREAD

**Issue by The-Compiler** [akrennmair/newsbeuter#430]
When trying to build master with gcc 6.2.1 on Archlinux:

```
src/utils.cpp: In static member function ‘static bool newsbeuter::utils::try_fs_lock(const string&, pid_t&)’:
src/utils.cpp:262:19: error: ignoring return value of ‘int ftruncate(int, __off_t)’, declared with attribute warn_unused_result [-Werror=unused-result]
   ftruncate(fd, 0);
                   ^
src/utils.cpp:263:47: error: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Werror=unused-result]
   write(fd, pidtext.c_str(), pidtext.length());
                                               ^
src/utils.cpp: In static member function ‘static std::__cxx11::string newsbeuter::utils::run_program(char**, const string&)’:
src/utils.cpp:478:13: error: ignoring return value of ‘int pipe(int*)’, declared with attribute warn_unused_result [-Werror=unused-result]
  pipe(ipipe);
             ^
src/utils.cpp:479:13: error: ignoring return value of ‘int pipe(int*)’, declared with attribute warn_unused_result [-Werror=unused-result]
  pipe(opipe);
             ^
src/utils.cpp:501:49: error: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Werror=unused-result]
   write(ipipe[1], input.c_str(), input.length());
                                                 ^
src/utils.cpp: In static member function ‘static int newsbeuter::utils::mkdir_parents(const string&, mode_t)’:
src/utils.cpp:1034:2: error: ‘result’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  if (result == 0) mkdir(p.c_str(), mode);
  ^~
cc1plus: all warnings being treated as errors
make: *** [Makefile:111: src/utils.o] Error 1
```

**Comment by Minoru** [comment]
Interesting: `-Wunused-result` is on by default and I'm not getting any warnings or errors, neither locally nor on Travis ([just added 6.2.0](https://travis-ci.org/akrennmair/newsbeuter/jobs/177947350#L173).) In the same vein, `-Wmaybe-unitialized` is enabled because we have `-Wall`, but no warnings or errors locally or on Travis.

Is my setup completely broken, or is yours more sophisticated than vanilla gcc? What's this thing, `cc1plus`, that you're using to compile things?

**Comment by Minoru** [comment]
(I'll fix those warnings, of course; but I'm interested to know how come I can't reproduce them.)

**Comment by The-Compiler** [comment]
I have no idea - I simply use [this PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=newsbeuter-git) on Archlinux which does nothing out of the ordinary.

I don't have a `cc1plus` in path, but there's a `/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/cc1plus` - so I guess gcc simply invokes that.

I think the most likely difference is GCC versions.

**Comment by Minoru** [comment]
Cracked it! Optimizations. We don't enable them by default, but Arch probably does. I could get the same warnings with gcc 4.9.3 on Funtoo when I passed `-O`.

I'll have to look into this a bit more to decide if we should test for all possible optimization levels from now on or what.

…And I still need to fix those warnings. Thanks for reporting, and stay tuned ☺

**Comment by The-Compiler** [comment]
That sounds likely, I use `CXXFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong"`.

What about just testing no/full optimization on Travis maybe?

**Comment by Minoru** [comment]
> What about just testing no/full optimization on Travis maybe?

What if there's a warning that's only triggered at, say, `-O2`? I think I'll just google around to see if there's any reports of such things, and if there isn't, I'll do just as you say.
