### ISSUE TITLE
Overriding CXXFLAGS causes them to duplicate

### ISSUE THREAD

**Issue by Minoru** [akrennmair/newsbeuter#431]
**Newsbeuter version (copy from `newsbeuter -v`)**: 0122a2e5b252053b3f357b30b50636faef91b4b5

Steps to reproduce the issue:

1. `export CXXFLAGS="-O3"`

2. `make`

This causes `make` to run the compiler as follows (there's a copy of `CXXFLAGS` after includes):

```
g++ -O3 -std=c++11 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/local/share/locale\" -DGIT_HASH=\"0122-dirty\"   -I/usr/include/libxml2    -I/usr/include/json-c   -I/usr/include/ncursesw   -O3 -std=c++11 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/local/share/locale\" -DGIT_HASH=\"0122-dirty\" -o src/configcontainer.o -c src/configcontainer.cpp
```

whereas if I don't have `CXXFLAGS` set, the invocation looks like this:

```
g++ -std=c++11 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/local/share/locale\" -DGIT_HASH=\"0122-dirty\"   -I/usr/include/libxml2    -I/usr/include/json-c   -I/usr/include/ncursesw   -o src/configcontainer.o -c src/configcontainer.cpp
```

**Comment by Minoru** [comment]
In #530, @tsipinakis [writes](https://github.com/akrennmair/newsbeuter/pull/540#issuecomment-296638293):

> If `config.mk` doesn't exist, `config.sh` is called by `make` which adds `CXXFLAGS+=$CXXFLAGS` to `config.mk` which is intended to append user-defined overrides to the flags, but `make` by default does not export its own variables **unless** they have been already set, in which case, it updates the values with whatever modifications happened within the makefile.
>
> So if `CXXFLAGS` is not set, it's not exported so config.mk does not contain an extra copy of the flags and the bug does not happen. But if it is, it is updated with all the extra flags added inside the makefile, which results in 2 copies of `CXXFLAGS`, one from the makefile and one from the config.mk inclusion.

**Comment by Minoru** [comment]
the  change that's causing this was introduced in 450942949ef1d96c669c8f26f0d3220274de417f. If I understand it correctly, the point was to make it easier to build Newsbeuter with custom `CXXFLAGS`: one could do something like `CXXFLAGS='blah blah' make` once and then just use `make`, because `CXXFLAGS` were preserved in the `config.mk`.

Does anyone actually rely on this behaviour? I don't. I'll gladly revert the aforementioned commit and be done with it.

**Comment by x4121** [comment]
As a user I would find this behavior confusing. I don't write c/c++ a lot so this might just be my unfamiliarity, but I would expect `CXXFLAGS='blah blah' make` to only apply the flags for this single call. For such behavior I would expect something like `./configure --foo=bar` (or `config.sh` in this project).
