### ISSUE TITLE
Error: an instance of newsbeuter is already running (PID: 0)

### ISSUE THREAD

**Issue by The-Compiler** [akrennmair/newsbeuter#432]
With aaa3d370e4a38b6c70e506e067471c33d2d0e55d I can now build again, but when starting newsbeuter, I get "Error: an instance of newsbeuter is already running (PID: 0)".

When I remove `~/.local/share/newsbeuter/cache.db.lock` and try again, the file gets created, but I get the same error again.

**Comment by Minoru** [comment]
Thanks for catching this!
