### ISSUE TITLE
Adding accent as a flag makes another flag disappear

### ISSUE THREAD

**Issue by tkerdonc** [akrennmair/newsbeuter#437]
**Newsbeuter version **: 2.10

Observed in PR #420 , including '"' in the flag list passed to OP_EDITFLAGS removes one of the other flags added alongside it.

**Comment by tkerdonc** [comment]
Link to failing test https://travis-ci.org/akrennmair/newsbeuter/builds/178662835

**Comment by Minoru** [comment]
Changed the title because the accent wasn't visible there.

**Comment by Minoru** [comment]
Fixed by #440.
