### ISSUE TITLE
Using a letter twice in an item's flags will cause some of them to be omitted

### ISSUE THREAD

**Issue by tkerdonc** [akrennmair/newsbeuter#438]
**Newsbeuter version **: 2.10

Observed in #420 using a letter twice will cause the following ones to be omitted. The numbers of omission depends on the letter's place in the sorted flag list.
e.g ABCDEFGB will end up being ABEFG

**Comment by tkerdonc** [comment]
Link to failing test https://travis-ci.org/akrennmair/newsbeuter/builds/178662835

**Comment by Minoru** [comment]
BTW, did you ensure that it's indeed *all flags* that trigger the issue? There are other possibilities:
* some flags might just be ignored;
* there might be a limit to the number of flags an article can have.

**Comment by tkerdonc** [comment]
So, this is a bit embarrassing, but turns out there was a typo in my original test, wrote a second 'F' instead of the 'J', all letters do pass without problem. 
On the plus side though, there indeed is a problem of tags disappearing when a letters is added a second time, #440 demonstrates it and provides a fix.
Editing the title and description
