### ISSUE TITLE
Suggestion for cursor positioning

### ISSUE THREAD

**Issue by AndreiUlmeyda** [akrennmair/newsbeuter#446]
newsbeuter 2.9
System: Linux 4.8.11-1-ARCH (x86_64)
Compiler: g++ 5.3.0
ncurses: ncurses 6.0.20161112 (compiled with 6.0)
libcurl: libcurl/7.51.0 OpenSSL/1.0.2j zlib/1.2.8 libssh2/1.8.0 (compiled with 7.46.0)
SQLite: 3.15.2 (compiled with 3.9.2)
libxml2: compiled with 2.9.2

1. in any long list of articles

2. going up and down the list moves the visible list only after reaching the top or bottom

Pacing through a long list is way faster to me if I can see a few articles ahead which stops being the case after the first screen (made worse by the fact that my newsbeuter window is usually only 10 lines or so in height).

Is it possible to keep the cursor in the middle of the list as long as the list longer than one page? Alternatively, if there was a "move-list-up/down" command, this behaviour could be achieved with key bindings.

Cheers again

**Comment by Minoru** [comment]
Sounds like your use-case can also be covered with #191

**Comment by AndreiUlmeyda** [comment]
Correct! Sry, missed that issue.
