### ISSUE TITLE
"STFL Parser Error near '}'" and aborts

### ISSUE THREAD

**Issue by k7k7** [akrennmair/newsbeuter#447]
**Newsbeuter version (copy from `newsbeuter -v`)**:
newsbeuter 2.10-cc6a
System: Linux 4.9.0-rc8 (x86_64)
Compiler: g++ 6.2.1 20161124
ncurses: ncurses 6.0.20161126 (compiled with 6.0)
libcurl: libcurl/7.51.0 GnuTLS/3.5.7 zlib/1.2.8 libssh2/1.7.0 nghttp2/1.17.0 librtmp/2.3 (compiled with 7.51.0)
SQLite: 3.15.2 (compiled with 3.15.2)
libxml2: compiled with 2.9.4

Steps to reproduce the issue:

1. Add https://btrfs.wiki.kernel.org/index.php?title=Special:RecentChanges&feed=atom

2. Reload and open it

3. Open "Talk:Deduplication"

**Other info you think is relevant**:
[backtrace.txt](https://github.com/akrennmair/newsbeuter/files/644574/backtrace.txt)

**Comment by Minoru** [comment]
Confirmed, thanks for reporting!

**Comment by Minoru** [comment]
Apparently I broke it in 26522a9315d5ee47be0ae2783d32331178eaaa7e.

**Comment by Minoru** [comment]
I believe this bug is fixed, but please check yourself.

You'll probably notice Newsbeuter doesn't display the table as nice as it could've; I filed #450 about that. Please subscribe there for updates (the button is in the toolbar on the right in "Notifications" area.)
