### ISSUE TITLE
[Poll] Do you use next-, prev- and close-dialog? (^V, ^G, ^X)

### ISSUE THREAD

**Issue by Minoru** [akrennmair/newsbeuter#459]
In 2008 Newsbeuter gained a new feature: users could now freely switch between
dialogs. For example, one could open save dialog and then quickly peek back at
the article to come up with a better filename. Or one could take a moment
while reading an article to go update the feeds to see if something more
important came up.

This is a nice feature, but it adds complexity to the code. I wonder if anyone
is really using it; maybe we can just get rid of it?

Just "yes" or "no" will be sufficient—I'm mostly interested in numbers here.

**Comment by flnds** [comment]
No.

I never used this feature and testing it now, I don't see a clear reason with it.
Neither "close-dialog" nor "^X" is anywhere to be found in the help-menu.

**Comment by Minoru** [comment]
>Neither "close-dialog" nor "^X" is anywhere to be found in the help-menu.

Indeed! Thanks for catching that; if we decide to keep the feature, I'll open an issue about this and fix it.

**Comment by tsipinakis** [comment]
Yes

I mostly use it when listening to a podcast, I find it useful to have the show notes/sources open in one dialogue and go back to the feedlist to do something else while still being able to easily switch back if I hear something I'm interested in.

**Comment by protist** [comment]
No. I primarily use Newsbeuter to store my headlines, that I'll read on my web browser. I don't use the dialog-navigation functionality.

**Comment by Minoru** [comment]
I'm going to close the poll on February 1st (i.e. in a little over a week). Please vote if you didn't yet!

**Comment by GADZPMYRJ** [comment]
No. I don't use them because I don't need these features.

**Comment by GordStephen** [comment]
No, I just navigate the tree with open/close.

**Comment by der-lyse** [comment]
No, I almost always open my "unread articles" query feed and then walk through all the articles with the next-unread function and finally close the query feed again.

**Comment by Minoru** [comment]
Hi everyone,

The poll is now over. To recap, the question was: is anyone using `next-`, `prev-` and `close-dialog` (`^V`, `^G`, and `^X` keys)?

We've had 9 participants (7 here in the issue tracker, 2 on the mailing list). One didn't explicitly vote but said that he wasn't aware of the features; this means he wasn't using them, which is good enough for the purposes of this poll. Another didn't explicitly vote but gave :+1: to a comment voting "no"; I'll have to assume this means "me too", i.e. "no".

Just one person voted "yes". This person also described his use-case: keeping the shownotes accessible while listening to a podcast. I like it.

Thus my decision is to **keep these features**.

Thank you to everyone who participated!

@flnds, the issue I promised to open is here: #490.
