### ISSUE TITLE
Add the possibility to set by default the sort options available as interactive operations

### ISSUE THREAD

**Issue by joedicastro** [akrennmair/newsbeuter#46]
In the config file you can sort the feeds by its first tag, but you can't sort them by the number of unread articles, for example.

The first action that I do each time that newsbeuter finish to catch the news is sort the feeds by the number of unread articles in descendent order. I suppose that most of us prefer this or another order to begin the reading of the articles in a convenient order. 

It will be lovely if this could be done automatically by default instead of doing it by hand. I can live without that, but you can make more lazy and happy if I don't have to sort them by hand anymore.

I suggest to make this via the `feed-sort-order` command in the config file, simply adding more options.

Thanks for your time.

**Comment by gpakosz** [comment]
:+1: 

I would like to see this happening as well. After having read https://github.com/akrennmair/newsbeuter/blob/b78990c65e648a93bc910c85c855dacbffb1dcbc/src/feedlist_formaction.cpp#L135 I tried to add `feed-sort-order unreadarticlecount-desc` to my config file without much success.

**Comment by Minoru** [comment]
Have any of you tried this with HEAD? It works for me =\

**Comment by Minoru** [comment]
(Well, the order seems to be backwards, but that's another issue.)

**Comment by gpakosz** [comment]
Sorry for the late follow up. It doesn't work for me.

I have `feed-sort-order unreadarticlecount-desc` in `config` and upon launch I still have to hit `G-u`

**Comment by Minoru** [comment]
Better late than never :)

Okay, so I built the commit you mentioned, copy-pasted the setting from your comment, and my feeds were sorted in ascending order of unread count.

If you didn't do any rebinding, `G` followed by `u` will *reverse* sort the feeds, which is equivalent to `feed-sort-order unreadarticlecount-asc`. I checked and it works, too.

So the question is: what do you mean by "doesn't work"? Do you mean that the order is wrong (ascending instead of descending), or do you mean that the feeds are sorted not by unread count but by something else?

**Comment by gpakosz** [comment]
I uninstalled newsbeuter and installed it again with `brew install --HEAD newsbeuter`.

When newsbeuter launches, I would like my feeds to be sorted without resorting to hitting `G` then `u`.

Here is what I get upon launching newsbeuter:
![image](https://cloud.githubusercontent.com/assets/553208/18642160/e0692206-7e9f-11e6-95f1-b29c14ad9c88.png)

And here is what I would like to see:
![image](https://cloud.githubusercontent.com/assets/553208/18642187/f34ec1a0-7e9f-11e6-9047-8a85573c611b.png)

Here is my config: https://github.com/gpakosz/.newsbeuter/blob/master/config

**Comment by Minoru** [comment]
Ah, I see. Well, as I said, `G` `u` is not the same as `unreadarticlecount-desc`. Use `unreadarticlecount-asc` instead. (And write back if that still isn't what you want.)

You'll bump into another problem, though: your four query feeds will always be at the bottom. I filed #362 about that; subscribe to it to receive notifications when I fix it (the Subscribe button is at the lower right of the issue text). Think I'll look into it in a few hours.

**Comment by Minoru** [comment]
Judging by the comments in #362, this issue can be closed now.

**Comment by gpakosz** [comment]
Well I can't really comment for OP. Still I a bit surprised I need to use `unreadarticlecount-asc` and not `unreadarticlecount-desc`. The end result is what I would have called descending order (from 9 to 0) as general definitions go.

**Comment by Minoru** [comment]
We can always re-open the issue if OP turns up and says it isn't fixed :)

You're totally right about the order. Changing it will force us to make a major release, which I don't really want at the moment—we have a ton of tiny bugs and rough corners, and our release process sucks at the moment (2.10 has been ready for 3 months, but haven't been officially released).
