### ISSUE TITLE
MIT Technology review rss feeds don't show up

### ISSUE THREAD

**Issue by abhixec** [akrennmair/newsbeuter#460]
**Newsbeuter version (copy from `newsbeuter -v`)**:2.9

Steps to reproduce the issue:

1.  Edit the URLS file and add : https://www.technologyreview.com/stories.rss
2.  Reload the url when the newsbeuter app. it shows 0/0

**Comment by Minoru** [comment]
On 6 January 2017 04:42:57 GMT+03:00, Abhinav <notifications@github.com> wrote:
>**Newsbeuter version (copy from `newsbeuter -v`)**:2.9
>
>Steps to reproduce the issue:
>
>1.  Edit the URLS file and add :
>https://www.technologyreview.com/stories.rss
>2.  Reload the url when the newsbeuter app. it shows 0/0 

Sorry, my computer died and I can't check this right now.

One thing you can do is build from Git and check if the bug is still present there.

--
Regards,
Alexander Batischev

**Comment by Minoru** [comment]
I checked with 2.9 here and it pulled in 20 items.

What distro are you running?

Did you have this feed in your URLs file before?

Can you reproduce this with clean configuration? (Move your `cache.db`, `config` and `urls` files someplace else for a little while.)

**Comment by abhixec** [comment]
I am using MacOS
