### ISSUE TITLE
Filter by flag in feed view

### ISSUE THREAD

**Issue by protist** [akrennmair/newsbeuter#464]
**Newsbeuter version (copy from `newsbeuter -v`)**:
2.9
```
Compilation date/time: Dec  7 2015 04:47:17
System: Linux 4.8.13-1-ARCH (x86_64)
Compiler: g++ 5.3.0
ncurses: ncurses 6.0.20161224 (compiled with 6.0)
libcurl: libcurl/7.52.1 OpenSSL/1.0.2j zlib/1.2.8 libpsl/0.16.1 (+libicu/58.2) libssh2/1.8.0 (compiled with 7.46.0)
SQLite: 3.16.2 (compiled with 3.9.2)
libxml2: compiled with 2.9.2
```

Steps to reproduce the issue:

1. Attempt to filter by flags in the filter view.

**Other info you think is relevant**:
I've started using newsbeuter, and despite some misgiving about the lack of panes, I'm loving it! (Thank you!) However, I had one suggestion about filters.

Context: I sync with Tiny Tiny RSS, so that I can also read RSS on my phone. I often read an article on my phone, and then star it so that I can investigate it in more detail later on my proper computer.

If I use Tiny Tiny RSS's web GUI on my computer, it shows all the starred items in a folder at the top of the feed list. Thus, I can easily see when there are "pending" articles to read.

![tt-rss shows all starred items](https://cloud.githubusercontent.com/assets/646668/21948051/b0090736-da3c-11e6-8b19-1f50f17d3bb8.png)

However, newsbeuter can only filter by flags in the article view, meaning that you have to know in advance *which feed* contains the flags before finding flagged articles. It would be much more useful if newsbeuter could show *all* flagged articles.

Also, it would be useful if newsbeuter's feed view could include a list of filters with total count, similar to the feeds themselves, but I'm not sure if this is beyond the scope of the project. Cheers.

**Comment by Minoru** [comment]
On 14 January 2017 01:42:45 GMT+03:00, protist <notifications@github.com> wrote:
>**Newsbeuter version (copy from `newsbeuter -v`)**:
>2.9
>```
>Compilation date/time: Dec  7 2015 04:47:17
>System: Linux 4.8.13-1-ARCH (x86_64)
>Compiler: g++ 5.3.0
>ncurses: ncurses 6.0.20161224 (compiled with 6.0)
>libcurl: libcurl/7.52.1 OpenSSL/1.0.2j zlib/1.2.8 libpsl/0.16.1
>(+libicu/58.2) libssh2/1.8.0 (compiled with 7.46.0)
>SQLite: 3.16.2 (compiled with 3.9.2)
>libxml2: compiled with 2.9.2
>```
>
>Steps to reproduce the issue:
>
>1. Attempt to filter by flags in the filter view.
>
>**Other info you think is relevant**:
>I've started using newsbeuter, and despite some misgiving about the
>lack of panes, I'm loving it! (Thank you!) However, I had one
>suggestion about filters.
>
>Context: I sync with Tiny Tiny RSS, so that I can also read RSS on my
>phone. I often read an article on my phone, and then star it so that I
>can investigate it in more detail later on my proper computer.
>
>If I use Tiny Tiny RSS's web GUI on my computer, it shows all the
>starred items in a folder at the top of the feed list. Thus, I can
>easily see when there are "pending" articles to read.
>
>![tt-rss shows all starred
>items](https://cloud.githubusercontent.com/assets/646668/21948051/b0090736-da3c-11e6-8b19-1f50f17d3bb8.png)
>
>However, newsbeuter can only filter by flags in the article view,
>meaning that you have to know in advance *which feed* contains the
>flags before finding flagged articles. It would be much more useful if
>newsbeuter could show *all* flagged articles.
>
>Also, it would be useful if newsbeuter's feed view could include a list
>of filters with total count, similar to the feeds themselves, but I'm
>not sure if this is beyond the scope of the project. Cheers.

Have you tried query feeds? This sounds like a perfect job for them.

--
Regards,
Alexander Batischev

**Comment by protist** [comment]
Oh, I missed that in the documentation! That does sound perfect! However, I ran into a few problems. I wonder if it's something to do with querying feeds from tt-rss instead of the local `urls` file?

Specifically, I added the following two lines to the top of `~/.config/newsbeuter/urls`.
```
"query:Unread Articles:unread = \"yes\""
"query:Starred Articles:flags # \"s\""
```
I'm obviously more interested in the second line, but I used the first line from the example in the  documentation to test first. I opened newsbeuter. I could see the query feeds at the top, but the counts were incorrect.
```
0/ 0 Unread Articles
0/ 0 Starred Articles
2/66 Feed A
2/10 Feed B
```
Here, the two numbers represent the number of unread and total articles. You can see that the "Unread Articles" feed supposedly contains 0 unread and total articles. However, once I enter that query feed, I can see the expected four unread articles. I then `q` back to the article list, and the numbers have updated properly.
```
4/ 4 Unread Articles
0/ 0 Starred Articles
2/66 Feed A
2/10 Feed B
```
I can quit and restart newsbeuter, and the information is incorrect again. This incorrect count is especially important, since I use `show-read-feeds no`; here this query feed is hidden from the feed list.

I also tried to test with the second query feed, but I ran into similar problems with the counts being incorrect. In addition, the starring doesn't seem to sync with tt-rss. Specifically, I have the following in `~/.config/newsbeuter/config`

```
ttrss-flag-star "s"
```
I then go to the article, press `^e`, `s`, `Enter`, and it is flagged. (I can also see the article in the second query feed, after the workaround above.) However, after reloading feeds, I cannot see the star in tt-rss's web GUI. Similarly, articles that are starred in the tt-rss web GUI have no flag in newsbeuter after reloading feeds.

**Comment by Minoru** [comment]
Re incorrect counts: try prepopulate-query-feeds setting.

Re starring: it might just be the case that the sync I'd one-way, from Newsbeuter to TT-RSS. I'll take a look at the code in roughly 10 hours.

**Comment by protist** [comment]
> Re incorrect counts: try prepopulate-query-feeds setting.

Oops, sorry, missed that too. Perhaps that could be mentioned in the `4.7. Query Feeds` section? It works perfectly now.

> Re starring: it might just be the case that the sync is one-way, from Newsbeuter to TT-RSS. I'll take a look at the code in roughly 10 hours.

Thank you. However, it's not syncing for me either way.

**Comment by Minoru** [comment]
Sorry for the delay—my day turned out to be much busier than I anticipated.

> Perhaps that could be mentioned in the 4.7. Query Feeds section?

Good idea! Did that. Thanks.

> Apologies, it now does appear to be syncing from Newsbeuter to TT-RSS, but not the other way around.

Looked at the code, and indeed it doesn't look like we sync "starred" flag from TT-RSS to Newsbeuter. This is a separate issue, so I filed #466.

If you think query feeds solved the problem you originally had, you can close this issue. Thanks!

**Comment by protist** [comment]
>Sorry for the delay—my day turned out to be much busier than I anticipated.

No worries, you are still blazingly fast! Thank you for all your responses. I appreciate it.

Query feeds are excellent, but I just have one minor issue. In tt-rss's web GUI, the starred articles are treated differently from normal feeds. In general, there is an unread count next to feed names in the feed list. However, the starred articles have a total count instead. This makes sense to me, because I've always "read" the starred item in the first place, otherwise I wouldn't know to star them. (Or I've read the title, at least.)

Newsbeuter is more powerful, so it can show the unread *and* total counts, so this is moot. However, it hides the starred (read) feeds if `show-read-feeds no` and `show-read-articles no` are set. I was wondering if particular query feeds could be set up to still show the feed in the feed list if it contains any articles at all (read or unread), and similarly to show *all* articles it contains, in the article list.

**Comment by Minoru** [comment]
> I was wondering if particular query feeds could be set up

Unfortunately, no. This will change once we implement per-feed configuration (#158), but that's quite far in the future at the moment.

The best you can do at the moment is to create a macro that will toggle these two settings. Or just abandon the idea of hiding read articles and feeds, if that's not too bad for you.

**Comment by protist** [comment]
Okay, no worries. I did think that this feature might be a bit convoluted, and possibly a bit counter to the straightforward nature of Newsbeuter. Thanks again!
