### ISSUE TITLE
Submit new Homebrew fromula for version 2.6

### ISSUE THREAD

**Issue by Aeyoun** [akrennmair/newsbeuter#47]
Once version 2.6 is released, the issues from the [first submission](https://github.com/mxcl/homebrew/pull/4384) have been resolved. New dependencies: json-c, and the flags `LDFLAGS:  -L/usr/local/opt/gettext/lib` and `CPPFLAGS: -I/usr/local/opt/gettext/include` must be set. Tested thoroughly on OS X 10.7 and 10.8,  and the current master of newsbeuter version 2.6. should not have any problems being accepted.

**Comment by keith** [comment]
Looks like this can be closed.
