### ISSUE TITLE
Option to make random-unread to select titles only from current feed

### ISSUE THREAD

**Issue by GADZPMYRJ** [akrennmair/newsbeuter#472]
**Newsbeuter version (copy from `newsbeuter -v`)**:
Compilation date/time: Dec  7 2015 04:47:17
System: Linux 4.8.13-1-ARCH (x86_64)
Compiler: g++ 5.3.0
ncurses: ncurses 6.0.20161224 (compiled with 6.0)
libcurl: libcurl/7.52.1 OpenSSL/1.0.2j zlib/1.2.11 libpsl/0.16.1 (+libicu/58.2) libssh2/1.8.0 (compiled with 7.46.0)
SQLite: 3.16.2 (compiled with 3.9.2)
libxml2: compiled with 2.9.2

**Other info you think is relevant**:
Many times, I browse through tens of unread articles in my query feed. Very often, I find myself, suddenly, in another feed. It's very difficult to watch at the header of articles list for the number of unread articles  (making sure it's not 0) and then at currently selected title. That's why I think it would be a great idea to lock myself in the current feed. I thought about an option like same-feed-while-random-unread. I think it shouldn't matter if I'm browsing a feed or meta feed.

**Comment by Minoru** [comment]
We can also create a separate command that's just like `random-unread`, but limited to the current feed. I don't yet know which solution is better.

**Comment by GADZPMYRJ** [comment]
I, myself, like both.

**Comment by Minoru** [comment]
Oh, it turns out that setting `goto-next-feed` to `no` already does what you want. Sorry this isn't documented. I'll update the manual now.
