### ISSUE TITLE
Setlocale failed - language settings

### ISSUE THREAD

**Issue by supermensa** [akrennmair/newsbeuter#483]
**Newsbeuter version (copy from `newsbeuter -v`)**:
XDG: configuration directory '/Users/username/.config/newsbeuter' not accessible, using '/Users/username/.newsbeuter' instead.
newsbeuter 2.9 - http://www.newsbeuter.org/
Copyright (C) 2006-2010 Andreas Krennmair

newsbeuter is free software and licensed under the MIT/X Consortium License.
Type `newsbeuter -vv' for more information.

Compilation date/time: Sep 27 2016 05:30:27
System: Darwin 16.3.0 (x86_64)
Compiler: g++ 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)
ncurses: ncurses 5.7.20081102 (compiled with 5.7)
libcurl: libcurl/7.51.0 SecureTransport zlib/1.2.8 (compiled with 7.49.1)
SQLite: 3.16.2 (compiled with 3.14.2)
libxml2: compiled with 2.9.4
Steps to reproduce the issue:

Depending on the settings in OS X default terminal ```Set locale environment variables on startup``` gives me either the error  ```setlocale failed: Bad file descriptor``` or ```setlocale failed: No such file or directory```.  
  
The only way I can launch newsbeuter is using the command from [issue #4](https://github.com/posativ/homebrew-newsbeuter/issues/4):  
 ```LANG=en_US.UTF-8 newsbeuter```  

A fix is adding ```export LANG="en_US.UTF-8"``` to my .bash_profile, but this is the first time I've experienced this error, so is it possible to set this within the newsbeuter config?

**Comment by Minoru** [comment]
> is it possible to set this within the newsbeuter config?

No; this environment variable is supposed to be set by the system. If you want it to only apply to Newsbeuter, you can create a script that does `LANG=en_US.UTF-8 /usr/bin/newsbeuter`, name it `newsbeuter` and put it into some directory that's mentioned in your `PATH` (or create such a directory and add it to `PATH`).

> Depending on the settings in OS X default terminal Set locale environment variables on startup gives me either the error `setlocale failed: Bad file descriptor` or `setlocale failed: No such file or directory`.

What does `locale` command print out in both cases?

**Comment by supermensa** [comment]
locale output:
```
LANG="da_DK.UTF-8"
LC_COLLATE="da_DK.UTF-8"
LC_CTYPE="UTF-8"
LC_MESSAGES="da_DK.UTF-8"
LC_MONETARY="da_DK.UTF-8"
LC_NUMERIC="da_DK.UTF-8"
LC_TIME="da_DK.UTF-8"
LC_ALL=
```

I've tried it with en_uk and others, but same problem.

I don't know if the trouble is due to the latest version of OS X (10.12.2 Sierra), as I haven't had other problems with locale (usually happens in terminal with ```sssh``` if something is set wrong).

**Comment by Minoru** [comment]
Wait, output of `locale` is the same in both cases?

How did you install Newsbeuter?

Please try the following:
* search for "newsbeuter.mo" file on your computer;
* you'll find a few in directories with paths like "/usr/local/share/locale/ru_RU.UTF-8/newsbeuter.mo". Note the part before the language ("/usr/local/share/locale" in my example);
* try running Newsbeuter like this: `LOCPATH=/usr/local/share/locale newsbeuter`, substituting the path for the one you've found.

**Comment by supermensa** [comment]
- locale output when 
- I installed newsbeuter using homebrew
- These are all the .mo paths:

```
/usr/local/Cellar/newsbeuter/2.9_1/share/locale/zh_TW/LC_MESSAGES/newsbeuter.mo
/usr/local/Cellar/newsbeuter/2.9_1/share/locale/zh/LC_MESSAGES/newsbeuter.mo
/usr/local/Cellar/newsbeuter/2.9_1/share/locale/uk/LC_MESSAGES/newsbeuter.mo
/usr/local/Cellar/newsbeuter/2.9_1/share/locale/tr/LC_MESSAGES/newsbeuter.mo
/usr/local/Cellar/newsbeuter/2.9_1/share/locale/sv/LC_MESSAGES/newsbeuter.mo
/usr/local/Cellar/newsbeuter/2.9_1/share/locale/ru/LC_MESSAGES/newsbeuter.mo
/usr/local/Cellar/newsbeuter/2.9_1/share/locale/pt_BR/LC_MESSAGES/newsbeuter.mo
/usr/local/Cellar/newsbeuter/2.9_1/share/locale/pl/LC_MESSAGES/newsbeuter.mo
/usr/local/Cellar/newsbeuter/2.9_1/share/locale/nl/LC_MESSAGES/newsbeuter.mo
/usr/local/Cellar/newsbeuter/2.9_1/share/locale/nb/LC_MESSAGES/newsbeuter.mo
/usr/local/Cellar/newsbeuter/2.9_1/share/locale/it/LC_MESSAGES/newsbeuter.mo
/usr/local/Cellar/newsbeuter/2.9_1/share/locale/hu/LC_MESSAGES/newsbeuter.mo
/usr/local/Cellar/newsbeuter/2.9_1/share/locale/fr/LC_MESSAGES/newsbeuter.mo
/usr/local/Cellar/newsbeuter/2.9_1/share/locale/es_ES/LC_MESSAGES/newsbeuter.mo
/usr/local/Cellar/newsbeuter/2.9_1/share/locale/es/LC_MESSAGES/newsbeuter.mo
/usr/local/Cellar/newsbeuter/2.9_1/share/locale/de/LC_MESSAGES/newsbeuter.mo
```

There is no 'da_DK', but my OS X 'Language & Region settings' is set to 'English' as the primary language and using 'Denmark' as region, so I don't know if that would trigger the non-english newsbeuter locale anyway.

After a restart and commenting out ```export LANG="en_US.UTF-8"``` from my .bash_profile, this is the output of ```locale```:

```
LANG=
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

- I can't get newsbeuter using ```LOCPATH=...```

**Comment by Minoru** [comment]
> There is no 'da_DK'

That's expected; Newsbeuter isn't translated into Danish (yet. Wanna contribute? :)

> but my OS X 'Language & Region settings' is set to 'English' as the primary language and using 'Denmark' as region, so I don't know if that would trigger the non-english newsbeuter locale anyway.

As far as I understand, it shouldn't.

New output of `locate` looks sane enough. What error are you getting now when you try to start Newsbeuter?

> I can't get newsbeuter using `LOCPATH=...`

Can you elaborate? Are you getting any errors? To be clear on this: you should use `LOCPATH=/usr/local/Cellar/newsbeuter/2.9_1/share/locale newsbeuter`. (I haven't found confirmation that `LOCPATH` is supported on OS X, though.)

**Comment by supermensa** [comment]
I'm getting the error ```setlocale failed: No such file or directory``` when starting newsbeuter with or without ```LOCPATH```. 

---
Sure, I'll give a danish translation a go :)

**Comment by Minoru** [comment]
I see. Can you show the output `strace -e open newsbeuter 2>&1 | grep locale`?

**Comment by supermensa** [comment]
I don't have strace on os x, can I use dtrace?

```sudo dtrace -l open newsbeuter 2>&1 | grep locale```
gives me no output on locale.

**Comment by Minoru** [comment]
Yep, dtrace is fine, as long as it looks for what I think it's looking for :) My `strace` incantation was meant to display all calls to `open()` syscall. What I'm trying to do here is to see the path by which Newsbeuter is trying to find locales. Judging by the [Wikipedia article on DTrace](https://en.wikipedia.org/wiki/DTrace), the correct analog is this:

```console
$ dtrace -n 'syscall::open*:entry { printf("%s %s",execname,copyinstr(arg0)); }'
```

I don't have an OS X machine, though, so I can't vouch for this.

You're looking for something like this:
```
open("/usr/local/share/locale/en_US.UTF-8/LC_MESSAGES/newsbeuter.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/local/share/locale/en_US.utf8/LC_MESSAGES/newsbeuter.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/local/share/locale/en_US/LC_MESSAGES/newsbeuter.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/local/share/locale/en.UTF-8/LC_MESSAGES/newsbeuter.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/local/share/locale/en.utf8/LC_MESSAGES/newsbeuter.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/local/share/locale/en/LC_MESSAGES/newsbeuter.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
```

(it's actually okay for these calls to fail.) The paths are the important part—if they don't start with `/usr/local/Cellar/newsbeuter/2.9_1/share/locale`, Newsbeuter was compiled with wrong options.

**Comment by supermensa** [comment]
I tried uninstalling and reinstalling newsbeuter via homebrew, just in case.

When explicitly setting the language via .bash_profile, I catched this output:

`
newsbeuter      /usr/local/Cellar/gettext/0.19.8.1/share/locale/en_DK/LC_MESSAGES/messages.mo
newsbeuter      /usr/local/Cellar/gettext/0.19.8.1/share/locale/en/LC_MESSAGES/messages.mo
`

but without setting the language, and newsbeuter failing with ```setlocale failed: No such file or directory```, then this is the output.

`newsbeuter /usr/local/opt/gettext/lib/libintl.8.dylibnewsbeuter /usr/local/opt/sqlite/lib/libsqlite3.0.dylibnewsbeuter /usr/local/opt/libstfl/lib/libstfl.0.24.dylibnewsbeuter /usr/local/opt/json-c/lib/libjson-c.2.dylibnewsbeuter /dev/dtracehelpernewsbeuter /usr/local/binnewsbeuter /usr/local/binnewsbeuter /usr/local/bin/newsbeuternewsbeuter /etc/.mdns_debugnewsbeuter /System/Library/Preferences/Logging/Subsystems/com.apple.defaults.plistnewsbeuter /Library/Preferences/Logging/Subsystems/com.apple.defaults.plistnewsbeuter /etc/localtimenewsbeuter /usr/local/Cellar/gettext/0.19.8.1/share/locale/locale.aliasnewsbeuter /usr/local/Cellar/gettext/0.19.8.1/share/locale/en_DK/LC_MESSAGES/messages.monewsbeuter /usr/local/Cellar/gettext/0.19.8.1/share/locale/en/LC_MESSAGES/messages.monewsbeuter /usr/share/locale/UTF-8/LC_CTYPEnewsbeuter /usr/share/locale/en_DK/LC_MESSAGES/LC_MESSAGESnewsbeuter /usr/share/locale/en_DK/LC_MESSAGES/LC_MESSAGESnewsbeuter /usr/local/share/locale/en_DK/LC_MESSAGES/LC_MESSAGESdtrace: error on enabled probe ID 7 (ID 166: syscall::open:entry): invalid user access in action #2 at DIF offset 24`

which contains the unusual ``en_DK`` in `newsbeuter /usr/local/share/locale/en_DK/LC_MESSAGES`

**Comment by supermensa** [comment]
Using `export LANG="en_US.UTF-8"` instead of `export LANG="da_DK.UTF-8"` gives me this dtrace output:

```
/usr/local/Cellar/gettext/0.19.8.1/share/locale/locale.aliasnewsbeuter
/usr/local/Cellar/gettext/0.19.8.1/share/locale/en_US.UTF-8/LC_MESSAGES/messages.mo
newsbeuter /usr/local/Cellar/gettext/0.19.8.1/share/locale/en_US.utf8/LC_MESSAGES/messages.mo
newsbeuter /usr/local/Cellar/gettext/0.19.8.1/share/locale/en_US/LC_MESSAGES/messages.mo
newsbeuter /usr/local/Cellar/gettext/0.19.8.1/share/locale/en.UTF-8/LC_MESSAGES/messages.mo
newsbeuter /usr/local/Cellar/gettext/0.19.8.1/share/locale/en.utf8/LC_MESSAGES/messages.mo
newsbeuter /usr/local/Cellar/gettext/0.19.8.1/share/locale/en/LC_MESSAGES/messages.mo
newsbeuter /usr/share/locale/UTF-8/LC_CTYPEnewsbeuter /usr/share/locale/en_US.UTF-8/LC_MESSAGES/LC_MESSAGES
newsbeuter /usr/local/share/locale/en_US.UTF-8/LC_MESSAGES/newsbeuter.mo
newsbeuter /usr/local/share/locale/en_US.utf8/LC_MESSAGES/newsbeuter.mo
newsbeuter /usr/local/share/locale/en_US/LC_MESSAGES/newsbeuter.mo
newsbeuter /usr/local/share/locale/en.UTF-8/LC_MESSAGES/newsbeuter.mo
newsbeuter /usr/local/share/locale/en.utf8/LC_MESSAGES/newsbeuter.mo
newsbeuter /usr/local/share/locale/en/LC_MESSAGES/newsbeuter.mo
```

**Comment by Minoru** [comment]
(I've edited one of your latest messages to make the listing readable—it was strung out into one line.)

This part is really interesting:
```
newsbeuter /usr/share/locale/UTF-8/LC_CTYPE
newsbeuter /usr/share/locale/en_DK/LC_MESSAGES/LC_MESSAGES
newsbeuter /usr/share/locale/en_DK/LC_MESSAGES/LC_MESSAGES
newsbeuter /usr/local/share/locale/en_DK/LC_MESSAGES/LC_MESSAGES
dtrace: error on enabled probe ID 7 (ID 166: syscall::open:entry): invalid user access in action #2 at DIF offset 24
```

`en_DK` doesn't bother me because you said earlier that your system is really configured this way (using English language, but located in Denmark). What's interesting is that these calls never appear in *my* listings.

That said, I managed to make `setlocale` fail for me when I tried `LANG=fr_DK.UTF-8`. `en_DK.UTF-8` works fine for me. I so-o confused right now! I'll look deeper into what setlocale is supposed to do and get back to you when I have something to share.

**Comment by Minoru** [comment]
That was fast :) `locale -a` lists all supported locales, so I promptly checked mine:
```console
$ locale -a | egrep '(en|fr)_DK'
en_DK
en_DK.iso88591
en_DK.utf8
```

I got them from GNU libc:
```console
$ locale -av
-----8<-----8<-----8<-----8<-----8<-----
locale: en_DK           archive: /nix/store/q3wx1gab2ysnk5nyvyyg56ana2v4r2ar-glibc-2.24/lib/locale/locale-archive
-------------------------------------------------------------------------------
    title | English locale for Denmark
   source | Danish Standards Association
  address | Kollegievej 6, DK-2920 Charlottenlund, Danmark
    email | bug-glibc-locales@gnu.org
 language | English
territory | Denmark
 revision | 1.0
     date | 2000-06-29
  codeset | ISO-8859-1

locale: en_DK.iso88591  archive: /nix/store/q3wx1gab2ysnk5nyvyyg56ana2v4r2ar-glibc-2.24/lib/locale/locale-archive
-------------------------------------------------------------------------------
    title | English locale for Denmark
   source | Danish Standards Association
  address | Kollegievej 6, DK-2920 Charlottenlund, Danmark
    email | bug-glibc-locales@gnu.org
 language | English
territory | Denmark
 revision | 1.0
     date | 2000-06-29
  codeset | ISO-8859-1

locale: en_DK.utf8      archive: /nix/store/q3wx1gab2ysnk5nyvyyg56ana2v4r2ar-glibc-2.24/lib/locale/locale-archive
-------------------------------------------------------------------------------
    title | English locale for Denmark
   source | Danish Standards Association
  address | Kollegievej 6, DK-2920 Charlottenlund, Danmark
    email | bug-glibc-locales@gnu.org
 language | English
territory | Denmark
 revision | 1.0
     date | 2000-06-29
  codeset | UTF-8
-----8<-----8<-----8<-----8<-----8<-----
```

What do these commands say on your machine?

**Comment by supermensa** [comment]
`
$ locale -a | egrep '(en|fr|da)_DK'
da_DK
da_DK.ISO8859-1
da_DK.ISO8859-15
da_DK.UTF-8
`
OS X doesn't support `locale -av`.. but should be the same.

This might be where the problem is though regarding `en_DK`:

* Inside Language & Region > Preferred languages, I change the Region from 'Denmark'
to 'United States' I can start newsbeuter with no problem.

* If I change the region to 'Sweden' the same problem arises and I can't start newsbeuter (set locale failed: No such file or directory / setlocale failed: Bad file descriptor - depending on `set locale environment variables on startup` on or off in terminal preferences.

**Comment by Minoru** [comment]
Okay, so this (I mean the output of `locale | grep`) means your system simply doesn't support en_DK locale. I don't know enough about this stuff to explain how it manages to otherwise work flawlessly :) I don't think I can help you any further, save for repeating [my advice about wrapping Newsbeuter in a script](https://github.com/akrennmair/newsbeuter/issues/483#issuecomment-275911354).

**Comment by supermensa** [comment]
Yeah, I can't find any reason why `en_DK` shouldn't be supported on OS X Sierra, but read in a related issue that "This is what .bash_profile is for..", so I agree to close this as this is an easy fix. Thanks for your all your help!
