### ISSUE TITLE
Folder Structure / Combined Feedlist

### ISSUE THREAD

**Issue by kyyu** [akrennmair/newsbeuter#487]
Hello, I'm trying newsbeuter (coming from QuiteRSS) but I'm having difficulty structuring my feeds.
I used a traditional 3-pane layout, with my feedlist being structured by folders (which function as groups).
eg:
```
┌TECH FOLDER
├feed
├feed
└─┬OS FOLDER
  ├feed
  ├feed
  └─┬SECURITY FOLDER
    ├feed
    └feed
┌YOUTUBE FOLDER
├feed
├feed
```
This system offers several benefits over a pure feedlist but the primary benefit is that when you select a folder, all feeds within that folder & sub-folders are combined in the article list.
eg. selecting the "OS" folder combines all feeds under "OS" & "SECURITY" (but excluding "YOUTUBE") in the article list.

I couldn't find anything related in the docs apart from the tagging system which seems very powerful but also very time-consuming if you have more than a couple feeds.

Does this functionality exist and if not, could you add it please?

**Comment by Minoru** [comment]
> I couldn't find anything related in the docs apart from the tagging system which seems very powerful but also very time-consuming if you have more than a couple feeds.

How are tags time-consuming?

I suspect you're trying to migrate your URLs by hand. Don't do that; use OPML export in QuiteRss and OPML import in Newsbeuter. QuiteRSS should export your folders, and Newsbeuter will automatically map them into tags. (IIRC they'll be like "TECH FOLDER/OS FOLDER/SECURITY FOLDER", but you can split them easily enough with `sed`.)

> Does this functionality exist and if not, could you add it please?

If by "this functionality" you mean folders, then no and no; we already have tags and we're confident they're fine, even if unusual to people who are used to folders.

If you mean combined feedlist, then yes, it exists already. Tag your feeds and select a tag; it works pretty much the same as folders.

**Comment by kyyu** [comment]
Hi, I don't think I explained this very well, here's the process of checking the latest from youtube:

**QuiteRSS**:
1) select YOUTUBE folder
2) update feeds

**Result**:
```
<date>		<channel>	<name of video/feed>
17.01.30	Channel 493	VideoName
17.01.29	Channel 121	AnotherVideoName
17.01.28	Channel 762	YetAnotherVideoName
```
Now I have a combined, updated list of all youtube videos ordered with the most recent at the top.

**newsbeuter**:
1) access tags
2) scroll down to the bottom of the list or access the console & type the number (18 in my case)
3) select YOUTUBE
4) update feeds (with "reload-only-visible-feeds" this works as expected)
5) ?

**Result**:
```
<channel>
Channel A
Channel B
Channel C
```
Now I have isolated the youtube feeds from the main feedlist, but they're still individual feeds.
Hopefully this clears it up, thanks for your reply.

**Comment by tsipinakis** [comment]
> Now I have isolated the youtube feeds from the main feedlist, but they're still individual feeds.

The currect query feed feature seems to be what you need in this case. If your feeds are tagged `youtube` for example

> "query:Youtube:tags # \"youtube\""

Will create a feed with all the youtube entries.

**Comment by kyyu** [comment]
Awesome, this is much better thank you.  `"query:Youtube:tags # \"YouTube\""` produced the desired result.

I know now how to effectively sort the feeds with a query, the next stage is figuring out how to reload a specific query.
- Pressing `r` while the Youtube query is highlighted does not reload all of youtube tagged content.
- After selecting the Youtube query, `R` is unavailable.

Is this intentional? Reloading several thousand feeds when I only need a specific set seems a little over the top.

**Comment by Minoru** [comment]
> Pressing r while the Youtube query is highlighted does not reload all of youtube tagged content.

Correct. Youtube query feed doesn't really contain anything; it loads articles from other feeds. Thus, these other feeds should be updated before Youtube query feed can be updated.

> After selecting the Youtube query, R is unavailable.

`R` isn't available inside feeds, thus it's not available inside query feeds.

But I see your logic there. I'll have to meditate on this a bit.

> Reloading several thousand feeds when I only need a specific set seems a little over the top.

Did you know you can miss articles if the feed is active enough and you update it rarely enough? Why not just auto-update everything?

And if you want up-to-the-minute news, you can just hit `R` in the feedlist. Newsbeuter implements all kinds of caching and won't put too much strain on servers (updating every minute might still be unwise, though). See also `reload-threads` setting to speed things up.

**Comment by kyyu** [comment]
Thanks, when you have so many feeds on so many topics and a poor connection it makes sense. Furthermore I don't want constant updates due to how distracting those systems are.

After setting up a config and some queries it's really nice, the macros are especially useful. 
I really hope updating queries will be possible in the near future.

**Comment by Minoru** [comment]
Since the initial question in this issue is solved, I'm closing it. The discussion about reloading query feeds was split to #491.
