### ISSUE TITLE
Article stays marked as unread when using external pager

### ISSUE THREAD

**Issue by KlausFabritius** [akrennmair/newsbeuter#495]
**Newsbeuter version (copy from `newsbeuter -v`)**:

newsbeuter 2.10-4afc
System: Linux 4.9.6-1-ARCH (x86_64)
Compiler: g++ 6.3.1 20170109
ncurses: ncurses 6.0.20161224 (compiled with 6.0)
libcurl: libcurl/7.52.1 OpenSSL/1.0.2k zlib/1.2.11 libpsl/0.17.0 (+libicu/58.2) libssh2/1.8.0 (compiled with 7.52.1)
SQLite: 3.16.2 (compiled with 3.16.2)
libxml2: compiled with 2.9.4

**Steps to reproduce the issue:**

1. Configure external pager for article view in ```~/.newsbeuter/config```
```
 pager less %f
```
2. Start newsbeuter and open unread article (Mark "N")

3. After leaving the external pager, the article stays marked as unread ("N")

**Other info you think is relevant:**

The example above illustrates the problem by using less. I prefer using VIm as the pager (better control over colors/highlighting/key bindings). Problem is the same.

**Comment by Minoru** [comment]
Thanks for reporting! It fixed it; can you please rebuild and check?

**Comment by KlausFabritius** [comment]
Works great! Thank you!
