### ISSUE TITLE
Macros Don't Work

### ISSUE THREAD

**Issue by jonbobbly** [akrennmair/newsbeuter#497]
**Newsbeuter version (copy from `newsbeuter -v`)**:
XDG: configuration directory '/home/jonathon/.config/newsbeuter' not accessible, using '/home/jonathon/.newsbeuter' instead.
newsbeuter 2.9 - http://www.newsbeuter.org/
Copyright (C) 2006-2010 Andreas Krennmair

newsbeuter is free software and licensed under the MIT/X Consortium License.
Type `newsbeuter -vv' for more information.

Compilation date/time: Apr  3 2016 07:12:50
System: Linux 4.4.0-62-generic (x86_64)
Compiler: g++ 5.3.1 20160330
ncurses: ncurses 6.0.20160213 (compiled with 6.0)
libcurl: libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3 (compiled with 7.47.0)
SQLite: 3.11.0 (compiled with 3.11.0)
libxml2: compiled with 2.9.3

Steps to reproduce the issue:

1. Add this from the documentation (https://newsbeuter.org/doc/newsbeuter.html#_macro_support)
macro E set browser "echo %u >> ~/.newsbeuter/queue" ; open ; set browser "elinks %u"

2. Attempt to use it on any article by typing ,E as the documentation suggests.

3. The open command seems to be issued as Newsbeuter will open the article for viewing as if enter had been pressed, however, the file is not updated at all.

**Comment by tsipinakis** [comment]
`open` opens the article in pager, the correct command is `open-in-browser`. It's a mistake in the documentation that has since been [fixed](https://github.com/akrennmair/newsbeuter/blob/9b7bd0631d66eb194c248be6f042a2d6fc1af032/doc/newsbeuter.txt#L778).
