### ISSUE TITLE
Refresh on theoldreader errors

### ISSUE THREAD

**Issue by x4121** [akrennmair/newsbeuter#501]
**Newsbeuter version (copy from `newsbeuter -v`)**: 2.9

Steps to reproduce the issue:

1. Add config
```
urls-source "oldreader"
oldreader-login "me@domain.tld"
oldreader-passwordfile ~/.newsbeuter/password
```
(Tested with plain text password in config, same result)

2. Open newsbeuter

3. Hit `R`

4. Status should say `Error while retrieving http://theoldreader.com/reader/atom/tor/sponsored/b21c0c250e651babb9104d38?n=20: HTTP response code said error`

**Other info you think is relevant**: New newsbeuter installation with no config but the above. New "theoldreader"-Account that I made ~5 min ago with only one RSS feed. Error is displayed everytime I sync the feed or "The Old Reader Sponsored Posts". RSS feed is still synced, "The Old Reader Sponsored Posts" shows (0/0).

**Comment by Minoru** [comment]
That's been (silently) [fixed ](https://github.com/akrennmair/newsbeuter/commit/fccad71a21fadbfc0da4bfd1527de56ca03f67e5#diff-a973a225d6d848a4017e32ea22b6d26eR163) while working on #150. I don't know if ignoring this feed is The Right Solution, but it works and no one suggested a better approach yet.

**Comment by x4121** [comment]
Oh sorry, don't know how I didn't see this already closed Issue

**Comment by Minoru** [comment]
No worries, it was easy enough to miss—it didn't mention "Sponsored" feed specifically, and the symptoms were a bit different ;)

**Comment by mrzool** [comment]
I'm still having this issue (newsbeuter 2.9) and I'm not clear on the steps needed to fix it.

Newsbeuter loaded and retrieved all feeds successfully on the first run, but after that I just get `USERERROR: Error while retrieving http://theoldreader.com/reader/atom/... HTTP response code said error` on every feed and can no longer retrieve any update.

**Comment by Minoru** [comment]
@mrzool , the problem has been fixed in the repository here, but the fix hasn't been released yet. This means you'll have to build the newest version from source.

If you're on Arch or Gentoo, there's premade packages that'll do everything for you. I'm not sure about other distros, you'll have to check yourself.

**Comment by mrzool** [comment]
@Minoru Got it. Thanks.
