### ISSUE TITLE
Search is now case sensitive in 2.10 version

### ISSUE THREAD

**Issue by qoxxxx** [akrennmair/newsbeuter#520]
newsbeuter 2.10-20330
System: Linux 4.4.0-67-generic (x86_64)
Compiler: g++ 5.4.0 20160609
ncurses: ncurses 6.0.20160213 (compiled with 6.0)
libcurl: libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3 (compiled with 7.47.0)
SQLite: 3.11.0 (compiled with 3.11.0)
libxml2: compiled with 2.9.3

While the search seems fixed for queries, it is now case sensitive, everywhere. I'm guessing it's a bug since it used to be insensitive in 2.9, or is there now a way to make it insensitive ?

**Comment by qoxxxx** [comment]
Actually, only case sensitive in queries. Insensitive in "regular" feeds.

**Comment by Minoru** [comment]
That's an error; it should be case-insensitive for all feeds. The bug was introduced in 065a3ff91f.
