### ISSUE TITLE
error: ‘long unsigned int newsbeuter::openssl_mth_id_function()’ defined but not used

### ISSUE THREAD

**Issue by Earnestly** [akrennmair/newsbeuter#522]
When attempting to compile newsbeuter (https://github.com/akrennmair/newsbeuter/commit/20330eaf3441a47b1f1c0d0a134a2052fdc1ac74) I get the following errors:
```
g++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -std=c++11 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/local/share/locale\" -DGIT_HASH=\"20330\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_GNU_SOURCE -D_DEFAULT_SOURCE  -DHAVE_OPENSSL=1 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -o src/cache.o -c src/cache.cpp
src/utils.cpp:1149:22: error: ‘long unsigned int newsbeuter::openssl_mth_id_function()’ defined but not used [-Werror=unused-function]
 static unsigned long openssl_mth_id_function(void) {
                      ^~~~~~~~~~~~~~~~~~~~~~~
src/utils.cpp:1135:13: error: ‘void newsbeuter::openssl_mth_locking_function(int, int, const char*, int)’ defined but not used [-Werror=unused-function]
 static void openssl_mth_locking_function(int mode, int n, const char * file, int line) {
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Recently we switched to openssl 1.1.0e which is likely the cause for this breakage.
```
% openssl version
OpenSSL 1.1.0e  16 Feb 2017
```

Is there any other information or any suggestions about what I can do next?

**Comment by Minoru** [comment]
This is probably related to this entry in the [changelog for 1.1.0](https://www.openssl.org/news/changelog.html#x6):

>   *) OpenSSL now uses a new threading API. It is no longer necessary to
     set locking callbacks to use OpenSSL in a multi-threaded environment. There
     are two supported threading models: pthreads and windows threads. It is
     also possible to configure OpenSSL at compile time for "no-threads". The
     old threading API should no longer be used. The functions have been
     replaced with "no-op" compatibility macros.
     [Alessandro Ghedini, Matt Caswell]

Thanks for reporting! I'll look into fixing this tomorrow.

**Comment by Minoru** [comment]
I should really stop making such promises. Large PR got merged and ate all my computer time for the evening. This issue will have to wait a bit more.

**Comment by Earnestly** [comment]
I'm in no hurry, don't worry.  Thank you for looking into at all \o

**Comment by Minoru** [comment]
I don't have 1.1.0, so I can't test this locally (without building OpenSSL and Curl from source, at least). Can you please pull down `bugfix/522-openssl-new-threading-api` branch and see if it works for you?

**Comment by Earnestly** [comment]
With that branch I see two new errors of the same calibur:

```
src/utils.cpp:1152:22: error: ‘long unsigned int newsbeuter::openssl_mth_id_function()’ defined but not used [-Werror=unused-function]
 static unsigned long openssl_mth_id_function(void) {
                      ^~~~~~~~~~~~~~~~~~~~~~~
src/utils.cpp:1138:13: error: ‘void newsbeuter::openssl_mth_locking_function(int, int, const char*, int)’ defined but not used [-Werror=unused-function]
 static void openssl_mth_locking_function(int mode, int n, const char * file, int line) {
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Minoru** [comment]
> Perhaps you added one too many 0's?

Definitely looks like that! I pushed another commit removing last two zeroes—can you try it?

**Comment by Earnestly** [comment]
Compiling https://github.com/akrennmair/newsbeuter/commit/9e44cb564b31e21ecfc03582bc3b8a314e166a59 I get no errors or warnings and newsbeuter seems to function fine pulling feeds from https urls.  From what little I know, this seems to be a success. o/

**Comment by Minoru** [comment]
Thanks! Merged the fix into master.
