### ISSUE TITLE
Question regarding if conditions browser option and content linksO

### ISSUE THREAD

**Issue by throwaway217** [akrennmair/newsbeuter#527]
Is there any way I can change the behaviour of a macro depending on other parameters ?

For example I have:
browser "echo '%u'| xclip"
and I want it to to echo Link [1] from content if the entry is from feed X

Also how do get a hold of Link [1] from content ? I can't find anything in the documentation.

**Comment by Minoru** [comment]
> Is there any way I can change the behaviour of a macro depending on other parameters ?

No. Macros don't accept any arguments, they're executes as-is.

> Also how do get a hold of Link [1] from content ?

You can use `bookmark-cmd` in combination with `goto-url` (`#`), for example.

Can you describe what you're trying to achieve in the first place?

**Comment by throwaway217** [comment]
I have the following feed: 

http://hnapp.com/rss?q=type%3Astory%2Cask%2Cshow%2Clink%20score>400

and most of it's feed items look like this: 

Feed: http://hnapp.com/rss?q=type%3Astory%2Cask%2Cshow%2Clink%20score>400
Title: 538 – Iosevka – A Typeface for Code, from Code
Author: justinjlynn
Link: https://be5invis.github.io/Iosevka/
Date: Sat, 01 Apr 2017 05:03:57 +0200

538 points, 120 comments[1]

Links:
[1]: https://news.ycombinator.com/item?id=14009963 (link)

Now that you said macros can't accept arguments I'm basically looking for another way to echo that [1] link into xclip.

**Comment by Minoru** [comment]
I see. Well, the only idea I have is to invoke url selection dialog (`#` by default) and bookmark it (`^B`). Your bookmark script will look like this:

```shell
#!/bin/sh

echo "$*" | xclip
```

On an off chance that you're copying the link to open it in the browser, note that you can do it from the URL selecton dialog. For the first ten links you can do it even faster by pressing the corresponding digit (so in your case, just press `1` and the link will be opened in your `browser`.)

Does that solve your problem?

**Comment by throwaway217** [comment]
Yep, thanks.
