### ISSUE TITLE
Colours broken on latest ncurses 6.0 - patch 20170401

### ISSUE THREAD

**Issue by Earnestly** [akrennmair/newsbeuter#528]
```
newsbeuter 2.10-7159e
System: Linux 4.10.8-2-ARCH (x86_64)
Compiler: g++ 6.3.1 20170306
ncurses: ncurses 6.0.20170401 (compiled with 6.0)
libcurl: libcurl/7.53.1 OpenSSL/1.1.0e zlib/1.2.11 libpsl/0.17.0 (+libicu/58.2) libssh2/1.8.0 (compiled with 7.53.1)
SQLite: 3.18.0 (compiled with 3.18.0)
libxml2: compiled with 2.9.4
```

It's hard to explain but essentially the colours have changed since ncurses 20170401 which itself touched a lot of colour code:

```
Author: Thomas E. Dickey <dickey@invisible-island.net>
Date:   Sun Apr 2 01:27:53 2017 +0000

    ncurses 6.0 - patch 20170401
    
    + minor fixes for vt100+4bsd, e.g., delay in sgr for consistency -TD
    + add smso for env230, to match sgr -TD
    + remove p7/protect from sgr in fbterm -TD
    + drop setf/setb from fbterm; setaf/setab are enough -TD
    + make xterm-pcolor sgr consistent with other capabilities -TD
    + add rmxx/smxx ECMA-48 strikeout extension to tmux and xterm-basic
      (discussion with Nicholas Marriott)
    + add test-programs sp_tinfo and extended_color
    + modify no-leaks code for lib_cur_term.c to account for the tgetent()
      cache.
    + modify setupterm() to save original tty-modes so that erasechar()
      works as expected.  Also modify _nc_setupscreen() to avoid redundant
      calls to get original tty-modes.
    + modify set_curterm() to update ttytype[] data used by longname().
    + modify wattr_set() and wattr_get() to return ERR if win-parameter is
      null, as documented.
    + improve cast used for null-pointer checks in header macros, to
      reduce compiler warnings.
    + modify several functions, using the reserved "opts" parameter to pass
      color- and pair-values larger than 16-bits:
      + getcchar(), setcchar(), slk_attr_set(), vid_puts(), wattr_get(),
        wattr_set(), wchgat(), wcolor_set().
      + Other functions call these with the corresponding altered behavior,
        including chgat(), mvchgat(), mvwchgat(), slk_color_on(),
        slk_color_off(), vid_attr().
    + add new functions for manipulating color- and pair-values larger
      than 16-bits.  These are extended_color_content(),
      extended_pair_content(), extended_slk_color(), init_extended_color(),
      init_extended_pair(), and the corresponding sp-funcs.
```

For example, the main issue seems to be the foreground colours now being the same colour as the background making them essentially invisible.

Here is a screenshot of the `help` screen inside newsbeuter:

![newsbeuter](https://ptpb.pw/aDv2.png)

**Comment by Minoru** [comment]
Don't have any suggestions or estimates at this point. We don't even use ncurses itself—we employ STFL which does it for us. Looks like this one's going to be a tricky one to fix :(

**Comment by Earnestly** [comment]
For the moment I can seem to recover a kind of default set of colours using the following:

```
color listnormal white black
color background white black
```

This is in a `config` with no other `color` attributes set.

**Comment by Yamakaky** [comment]
I also have the same problem, only the selected line is visible. See https://lut.im/4tTXlhD3e1/gQxt85jBjlHt5xDN.png. The fix by @Earnestly works.

**Comment by protist** [comment]
I can confirm the problem and @Earnestly's fix, but one compounding issue is that `white` is not pure white on my default terminal, but a dull grey instead (#D3D7CF). I'm aware that I can change this in my terminal emulator's preferences, but I'm generally happy with its setting, and would prefer to hard code it for newsbeuter only.

I used to use `default` when applicable, which no longer works. I've now also tried color15 (#EEEEEC) and color255 (#EEEEEE), but neither is pure white (#FFFFFF).

I'm also getting some artefacts, but it's not 100% reproducible. I presume they are related to this issue. For example, with the following config
```
color background          black color255
color listnormal          color250 color255
color listfocus           color250 color229
color listnormal_unread   black color255
color listfocus_unread    black color229
color info                yellow blue bold
color article             black color255
```
I sometimes get residual `listfocus_unread` colouring, as per the following screenshot. Here the third item has focus, but the first item still has colouring artefacts.

![artefacts](https://i.imgur.com/6SGfym3.png)

**Comment by diskotechjam** [comment]
I'm having the same issue, whenever "default" is set as the background color, only "white" displays correctly. Setting all my background colors to "black" restores usability. 

> 
color 	background          white   black
color	listnormal          white   black
color	listfocus           yellow  black 		bold
color	listnormal_unread   red 	black
color	listfocus_unread    yellow 	black   	bold
color	info                green  	black	  	bold
color	article             white   black
>

**Comment by tomxtobin** [comment]
@protist You want `color231`.

**Comment by protist** [comment]
Oops, thanks @tomxtobin! For some reason, that looked a bit yellowish to me. That works well.

**Comment by Minoru** [comment]
I built 20170422 from source. Its own tests work fine.

Then I built libstfl—the library we use to draw the interface. its example has the same problems with colour as you report.

**Comment by Cloudef** [comment]
FYI, this also affects rtorrent-pyro as well. Seems like general ncurses breakage.

**Comment by Minoru** [comment]
@Cloudef, thanks! You actually gave me an idea to, well, search GitHub for the similar issues, and looks like the guys over at vifm/vifm#269 run into the same issue, find out the cause, devised a solution and [reported it upstream](https://lists.gnu.org/archive/html/bug-ncurses/2017-04/msg00035.html). And yeah, it does look like the `default` colour in Ncurses is now broken.

**Comment by Minoru** [comment]
When built against just-released [ncurses-6.0-20170429](https://lists.gnu.org/archive/html/bug-ncurses/2017-04/msg00037.html), STFL example works fine. Pretty sure that'll fix Newsbeuter too. (Testing Newsbeuter is a bit harder because it links Ncurses dynamically, not statically; so I didn't do it.)

**Comment by Earnestly** [comment]
Since ncurses 6.0.20170429 I can report that things appear to have returned back to normal:

[!newsbeuter help](https://ptpb.pw/8tUV)

**Comment by Minoru** [comment]
We can always re-open this if someone claims that it wasn't fixed. Thanks for reporting this in the first place!
