### ISSUE TITLE
SQLite schema

### ISSUE THREAD

**Issue by Yamakaky** [akrennmair/newsbeuter#535]
Just in case you don't know it, SQLite doesn't support `VARCHAR`, `INTEGER(1)` and such. https://sqlite.org/datatype3.html

**Comment by Minoru** [comment]
I'm aware of this, but don't think it matters too much. It's just the way SQLite stores stuff; what do I care? AFAIK we aren't using these things to enforce anything—if Newsbeuter needs some string to be X chars long, it does its checks in C++. SQLite can store them any way it wants as long as it can give us back the values we put into it :)

Am I missing anything? Are you aware of any problems that this creates for us?

**Comment by Yamakaky** [comment]
No, there is no problem, see https://sqlite.org/datatype3.html#determination_of_column_affinity for the conversion rules. It's just to be sure you don't rely on it in your code.

**Comment by Minoru** [comment]
Ah, okay. Thank you for caring! ^_^
