### ISSUE TITLE
disturbed colors (after ncurses was updated)

### ISSUE THREAD

**Issue by klartext** [akrennmair/newsbeuter#543]
There was update of ncurses, which seems to have disturbed all my colors.
I don't used color settings in config-file so far.
I now tried around with it to correct the view, but got no good results so far.
Just using the newsbeuter color-defaults created the mess with the new ncurses.

**Newsbeuter version (copy from `newsbeuter -v`)**:
newsbeuter 2.10-385a
System: Linux 4.10.11-1-ARCH (x86_64)
Compiler: g++ 6.3.1 20170306
ncurses: ncurses 6.0.20170401 (compiled with 6.0)
libcurl: libcurl/7.54.0 OpenSSL/1.1.0e zlib/1.2.11 libpsl/0.17.0 (+libicu/58.2) libssh2/1.8.0 (compiled with 7.54.0)
SQLite: 3.18.0 (compiled with 3.18.0)
libxml2: compiled with 2.9.4

**Comment by Minoru** [comment]
Thanks, but this is already reported as #528.
