### ISSUE TITLE
default background color impacts foreground color

### ISSUE THREAD

**Issue by Nanoseb** [akrennmair/newsbeuter#544]
**Newsbeuter version (copy from `newsbeuter -v`)**:
```
Compilation date/time: Mar  8 2017 21:56:57
System: Linux 4.10.11-1-ARCH (x86_64)
Compiler: g++ 6.3.1 20170306
ncurses: ncurses 6.0.20170401 (compiled with 6.0)
libcurl: libcurl/7.54.0 OpenSSL/1.1.0e zlib/1.2.11 libpsl/0.17.0 (+libicu/59.1) libssh2/1.8.0 (compiled with 7.53.1)
SQLite: 3.18.0 (compiled with 3.17.0)
libxml2: compiled with 2.9.4
```

Steps to reproduce the issue:
1. having `color listnormal white default` in the config file (or an empty config file)

**Other info you think is relevant**:
The default parameter on the background is impacting the foreground as well, with the config is set with `color listnormal white default` both the background and foreground are black however with `color listnormal white black` the expected behaviour is witnessed.

I tried in a tty, urxvt and terminator and the issue is the same.

It is indeed not a big issue since I can set the backgound to black by myself, but I thought it might be interesting to report because now without any config file the text is not readable.

**Comment by Minoru** [comment]
Hi; thanks for the report!

I'm pretty sure this is the same problem as #528. Can you please upgrade to ncurses 6.0.20170429 and check if the issue still exists?

**Comment by kyyu** [comment]
Had the same problem, It's ncurses. 
Either upgrade to 6.0.20170429 or downgrade to pre-6.0.20170401

**Comment by Nanoseb** [comment]
Indeed it seems to come from ncurses, I have downgraded to 6.020170128 and it works fine now. Thanks for the quick reply and thank you for maintaining/developing this piece of software!

**Comment by Minoru** [comment]
You're most welcome! ;)
