### ISSUE TITLE
Empty podbeuter list not cleared

### ISSUE THREAD

**Issue by antpli** [akrennmair/newsbeuter#546]
**Podbeuter version (copy from `podbeuter -v`)**:

I have seen the issue first with podbeuter 2.8 (Debian version),  but by comparing the source code I think it still exists.

**Newsbeuter version (copy from `newsbeuter -v`)**:

> Compilation date/time: Sep  2 2014 18:26:46
> System: Linux 3.16.0-4-amd64 (x86_64)
> Compiler: g++ 4.9.1
> ncurses: ncurses 5.9.20140913 (compiled with 5.9)
> libcurl: libcurl/7.38.0 GnuTLS/3.3.8 zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3 (compiled with 7.37.1)
> SQLite: 3.8.7.1 (compiled with 3.8.6)
> libxml2: compiled with 2.9.1

Steps to reproduce the issue:

1. start with an empty download queue
2. open newsbeuter and enqueue a podcast to the download queue by pressing "e"
3. open podbeuter, there should be the one entry added above, classified as "queued"
4. download the file by pressing "d", the entry is now classified as "ready"
5. delete the entry by pressing "D", the entry is now classified as "deleted"
6. try to clear the list by pressing "P":
  * I would expect that the list gets cleared, but the entry does not vanish
  * Trying to mark the entry as "finished" by pressing "m" and subsequently trying to clear the list by pressing "P" also does not work

**Other info you think is relevant**:

I think the line which is responsible for this behaviour is line 59 in src/pb_view.cpp of git 20da889 (line 52 in the Debian version 2.8):

```
59 if (ctrl->downloads().size() > 0) {
.. ...
80   dllist_form.modify("dls", "replace_inner", code);
81 }
```

If I understand correctly, the view is only updated if there are still some entries left which is not true in my case.  Is there any reasoning for this behaviour?

Would it be safe to just remove the check in line 59?

**Comment by Minoru** [comment]
The condition was added in 8e5cf9e5fb3 and hasn't been touched since. The commit message doesn't provide any rationale.

Podbeuter is underdeveloped and doesn't get much use (judging by the questions on IRC and reports here). So I'm not very much surprised that you've discovered a problem that was introduced a decade ago. Congrats on that, by the way ;)

I think removing the check is fine. Will you be able to do it yourself, recompile and test a bit? I don't use Podbeuter myself, so my testing will be sketchy at best.

**Comment by antpli** [comment]
I have modified, recompiled, and tested the Debian 2.8 version a few weeks ago and I use it since then. Here it seems to work.

**Comment by Minoru** [comment]
Oh, cool! Wanna submit a PR, or should I just commit the change? I'll credit you, of course.

**Comment by antpli** [comment]
Please just commit the change. 

Thank you for developing this software.

**Comment by Minoru** [comment]
Just committed the fix. Thanks for reporting this and providing the fix!
