### ISSUE TITLE
`bind-key j down` doesn't work for `tagselection` window

### ISSUE THREAD

**Issue by lwm** [akrennmair/newsbeuter#549]
```
newsbeuter 2.10-8e74
System: Linux 4.4.0-78-generic (x86_64)
Compiler: g++ 5.4.0 20160609
ncurses: ncurses 6.0.20160213 (compiled with 6.0)
libcurl: libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3 (compiled with 7.47.0)
SQLite: 3.11.0 (compiled with 3.11.0)
libxml2: compiled with 2.9.3
```

Steps to reproduce the issue:
1. Set `bind-key j down` in your config.
2. Run `newsbeuter` and type `t` (view tags).
3. Try to press `j` to move one tag down.

**Comment by lwm** [comment]
Also tested on latest `newsbeuter 2.10-98f6` version.

**Comment by lwm** [comment]
Ah, I have `bind-key j next` also, so it was a conflict!? Closing!

**Comment by Minoru** [comment]
Sorry I'm late; glad you solved it though!
