### ISSUE TITLE
[Feature Request] A way to fetch a subset of feeds at a time?

### ISSUE THREAD

**Issue by rieje** [akrennmair/newsbeuter#559]
I glanced at the docs, but I'm not sure how, if possible, to categorize feeds in such a way that you can access a feed list of all feeds in one "category" and only feeds in this category will update. For example, I may have hundred of feeds and have a category containing "news", "music", "linux", "movies", etc. Instead of seeing all of the feeds in one list, how about accessing these lists of feeds one list at a time and only when a feed list is focused will it update all feeds in that entire list? Doesn't have to be categories of the same topics--I can for example have a list of feeds which I prioritize most and only have those feeds automatically update, while the others I can select to manually update *as a whole*.

At the moment, Having all hundreds of feeds update at the same time is not ideal, nor is selecting a single feed and manually updating it. Something like what I've described allows for updating only a handful of feeds that are relevant to the user at that particular time, which is more efficient and relevant to the user.

If such an option is not available yet or desirable, then what is the closest way I can achieve this type of workflow? Maybe I described it poorly, but essentially I'm looking for a way to separate feeds in such a way that a group of feeds I can elect to automatically update while the rest I can choose to manually update (as groups of feeds, not individually).

**Comment by Minoru** [comment]
The closest you can get at the moment is to [tag](https://newsbeuter.org/doc/newsbeuter.html#_tagging) your feeds to categorize them and set [`reload-only-visible-feeds`](https://newsbeuter.org/doc/newsbeuter.html#idp49768544) to `yes`. You'll be able to view a tag (`t` key by default) and press `R` to update all the feeds in it. IIRC automatic update will still update all the feeds.

Is that what you wanted, or did I misunderstand the question?
