### ISSUE TITLE
read/unread flags not preserved when using alternative url file

### ISSUE THREAD

**Issue by mrzool** [akrennmair/newsbeuter#560]
*Newsbeuter v2.9*

Steps to reproduce the issue:

1. Start newsbeuter with an alternative url file (`newsbeuter -u path/to/file`)
2. Set some articles or feeds as "read", delete some other article, quit newsbeuter
3. Open newsbeuter using *another* alternative url file and quit
4. Open newsbeuter again using the first alternative url
5. Read flags got lost in the process, all feeds are unread again. Deleted articles are there again.

I don't think I've misconfigured anything, in any case here's my [config file](https://github.com/mrzool/dotfiles/blob/master/newsbeuter/.newsbeuter/config).

**Comment by mrzool** [comment]
I had forgot one step to reproduce. Updated the above comment accordingly.

**Comment by Minoru** [comment]
You should either:
* set `cleanup-on-quit` to `no`; or
* use separate cache files for each of our urls files.

What happens is:
1. with first urls file, you put some feeds into your cache file;
2. you close Newsbeuter. Nothing interesting happens at this point;
3. then you load the second urls file and put more feeds into the cache;
4. now when you quit Newsbeuter, it removes the feeds that aren't in the urls file—i.e. all the feeds that were added from the first urls file. This includes "read" statuses, flags and the like;
5. when you start Newsbeuter with the first urls file again, auto-update fetches the whole feeds again.

Hope this helps. Don't hesitate to add more details, and if this comment solved the issue, just close it.

**Comment by mrzool** [comment]
That solves it. Thanks a lot for the explanation!
