### ISSUE TITLE
Align article title properly for Chinese characters (and potentially other characters)

### ISSUE THREAD

**Issue by rieje** [akrennmair/newsbeuter#562]
There is [misalignment](https://ptpb.pw/ALA2vyzUj52IAI4El0yHTZyQ2nk4.png) when the RSS name is in Chinese characters. As you can see, each Chinese character is exactly 2 characters. So for each Chinese character, simply compensate it by shifting 1 space to the left  for the output of the article title seems it would fix this.

**Comment by Minoru** [comment]
I split the unrelated issue you reported here into #564.

The situation with Chinese characters is a bug. Thanks for reporting this!

**Comment by Minoru** [comment]
Closing this in favour of a #572, which is better presented. (The screenshot in this one already expired. I should've moved it to GitHub Issues—my bad.)
