### ISSUE TITLE
Getting "Error while saving bookmark" message when bookmarking succeeds

### ISSUE THREAD

**Issue by rlue** [akrennmair/newsbeuter#571]
**Newsbeuter version**: 2.9

Steps to reproduce the issue:

1. Install and configure [pocket-cli](https://github.com/rakanalh/pocket-cli).

2. In `~/.newsbeuter/config`:
   ```
   bookmark-cmd "~/.newsbeuter/add_to_pocket.sh"
   bookmark-autopilot yes
   ```

3. In `# ~/.newsbeuter/add_to_pocket.sh`:
   ```
   #!/bin/sh
   pocket-cli add --url "$1"
   ```

---

Given this setup, anytime I bookmark an article, I get the following error message on the newsbeuter command line:

    Error while saving bookmark: URL has been added

Meanwhile, the bookmarked article indeed appears in my Pocket list. I have confirmed that `pocket-cli add` normally exits with a status of 0.

**Comment by Minoru** [comment]
Apparently Newsbeuter uses the output, not the exit code, to detect the failure. (That was a surprise to me, too!) Quoting [the relevant section of the documentation](https://newsbeuter.org/doc/newsbeuter.html#_bookmarking):

> When everything went OK, the plugin simply exits. In case something goes wrong while saving the bookmark, it writes out an error message as a single line. This error message is then presented to the user from within newsbeuter.

I think you can rewrite your `~/.newsbeuter/add_to_pocket.sh` like this:

```sh
#!/bin/sh
temp=`mktemp add_to_pocket.XXX.log`
pocket-cli add --url "$1" >"$temp" 2>&1
if [ $? -ne 0 ]
then
    cat "$temp"
fi
rm -f "$temp"
```

This way it'll only report the output if the exit code was non-zero, which seems reasonable.

**Comment by rlue** [comment]
Wow, good eye!

I opted for the following, since it was a little more compact:

    pocket-cli add --url "$1" 2>&1 >/dev/null

This replaces STDOUT with STDERR altogether.

**Comment by Minoru** [comment]
I'd still advise you to keep at least *some* some sort of error:

```sh
pocket-cli add --url "$1" 2>&1 >/dev/null || echo "Error adding a bookmark"
```

You'll thank yourself later, when your network connection lapse for a moment and you realize that has it not been for the error message, you'd think you have the bookmark, only to discover a month later that in fact you don't ;)

**Comment by rlue** [comment]
Worth noting here is that `2>&1 >/dev/null` is different from `>/dev/null 2>&1`. The latter is probably what you're used to seeing, and silences all output from both STDOUT and STDERR. With the former, STDOUT is sent to the black hole and STDERR is redirected to (the actual) STDOUT. 

Using `||` is clever too, though.
