### ISSUE TITLE
Double-width unicode characters break fixed-length format string variables

### ISSUE THREAD

**Issue by rlue** [akrennmair/newsbeuter#572]
**Newsbeuter version**: 2.9

Steps to reproduce the issue:

1. Subscribe to some RSS feeds with Chinese titles, e.g.

   * https://www.ptt.cc/atom/marvel.xml "娛樂"
   * https://www.ptt.cc/atom/movie.xml "娛樂"
   * https://www.ptt.cc/atom/stupidclown.xml "娛樂"

2. View all articles (e.g., filter `guid =~ .*`)

The "feed name" column of the article list (_i.e.,_ the `%T` variable in the `articlelist-format` string) will be staggered, like so:

```
   1 N  Jun 26   102   |批踢踢實業坊 movie 板   |  [問片] 想找一部有點久的恐怖片
   2 N  Jun 26   864   |Reddit           |  [bspwm][ofx][OC] I love sci fi movie int
   3 N  Jun 26    78   |批踢踢實業坊 StupidClow|  Re: [無言] 保溫瓶上的英文
   4 N  Jun 26    82   |批踢踢實業坊 movie 板   |  Re: [請益] 老片 頂尖對決 的重大疑
```

(I know I can rename the feeds with a `~` tag, and that's probably what I'll do for now, but it would be nice to have the option to view Chinese characters. Thanks for an amazing piece of software, btw!)

**Comment by Minoru** [comment]
Thanks for a report! This has previously been reported in #562, but the screenshot there has expired, and your report is just better, so I'd keep it and close the other one.
