### ISSUE TITLE
xmllint error when building docs

### ISSUE THREAD

**Issue by maln0ir** [akrennmair/newsbeuter#586]
**Newsbeuter version**: commit d20cf49a5b83ed209ca08def2629aae669e16b08

Steps to reproduce the issue:

    $ LC_ALL=C make doc
    mkdir -p doc/xhtml
    a2x -f xhtml -D doc/xhtml doc/newsbeuter.txt
    a2x: ERROR: "xmllint" --nonet --noout --valid "/home/maln0ir/src/newsbeuter/doc/xhtml/newsbeuter.xml" returned non-zero exit status 4
    make: *** [Makefile:146: doc/xhtml/newsbeuter.html] Error 1

**Other info you think is relevant**:

    $ xmllint --version
    xmllint: using libxml version 20904
       compiled with: Threads Tree Output Push Reader Patterns Writer SAXv1 FTP HTTP DTDValid HTML Legacy C14N Catalog XPath XPointer XInclude Iconv ICU ISO8859X Unicode Regexps Automata Expr Schemas Schematron Modules Debug Zlib Lzma 

    $ a2x --version
    a2x 8.6.9

    $ xmllint --nonet --noout --valid doc/xhtml/newsbeuter.xml
    file:///etc/xml/catalog:1: parser error : Document is empty

    ^
    I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd
    doc/xhtml/newsbeuter.xml:2: warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
    D DocBook XML V4.5//EN" "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
                                                                                   ^
    doc/xhtml/newsbeuter.xml:6: validity error : Validation failed: no DTD found !
    <article lang="en">
                      ^

**Comment by Minoru** [comment]
Are you on OS X, by any chance? [We're setting](https://github.com/akrennmair/newsbeuter/blob/6c1dc60d68be4adfc8dcf9dee5f08fc8b21d7362/.travis.yml#L97) an environment variable `XML_CATALOG_FILES` in order to work around the same problem on Travis. You can do the same:
```
XML_CATALOG_FILES=/usr/local/etc/xml/catalog make doc
```

On Linux, I guess some package with DTDs should be installed, though we don't have anything like this in our Travis scripts. So what system are you on?

**Comment by maln0ir** [comment]
I'm using Arch Linux and it looks like I have DTDs installed, because "missing" `docbookx.dtd` file is available on my system:

    $ pacman -Ql docbook-xml | grep docbookx.dtd
    docbook-xml /usr/share/xml/docbook/xml-dtd-4.1.2/docbookx.dtd
    docbook-xml /usr/share/xml/docbook/xml-dtd-4.2/docbookx.dtd
    docbook-xml /usr/share/xml/docbook/xml-dtd-4.3/docbookx.dtd
    docbook-xml /usr/share/xml/docbook/xml-dtd-4.4/docbookx.dtd
    docbook-xml /usr/share/xml/docbook/xml-dtd-4.5/docbookx.dtd

Despite this, I still can't make `make doc` work, because I can't find right value for `XML_CATALOG_FILE` variable.

Something may be wrong on Arch side, it seems.

**Comment by Minoru** [comment]
[This thread](https://bbs.archlinux.org/viewtopic.php?id=176834) says you might need to reinstall `docbook-xml` to re-generate `/etc/xml/catalog`.

**Comment by maln0ir** [comment]
Thank you, that solved the problem.
