### ISSUE TITLE
Malformed feed title can break rendering

### ISSUE THREAD

**Issue by gpakosz** [akrennmair/newsbeuter#589]
**Newsbeuter version (copy from `newsbeuter -v`)**: newsbeuter 2.10-a3a7

Steps to reproduce the issue:

1. add `http://www.aerialmantis.co.uk/feed.xml` which title is `Gordon Brown on<br>C++, Gamedev, Heterogeneous Computing`

2. go back to the feed list

3. rendering is broken by `<br>`

![image](https://user-images.githubusercontent.com/553208/29220717-4485409a-7ebc-11e7-9ad7-c8fd58a219d4.png)

**Comment by Minoru** [comment]
Probably related: #554.

Thank you for the report, @gpakosz!
