### ISSUE TITLE
New release from time to time

### ISSUE THREAD

**Issue by klartext** [akrennmair/newsbeuter#594]
Hello,

it would be helpful to create a new release from time to time,
so that distributions / packagers can pick it and provide newer versions
from newsbeuter.
The last time a new release was created is Feb. 2015.
That's about two and a half year ago.

So, please create a new release, so that people, who want to use
pre-packaged releases could just use those and install with their package-manager.

Maybe releases could be provided in regular time intervals, if possible?

**Comment by carno** [comment]
https://github.com/akrennmair/newsbeuter/issues/525

**Comment by Minoru** [comment]
Closing this as duplicate of #525. Will post an update over there.
