### ISSUE TITLE
Feature request: Export url to buku

### ISSUE THREAD

**Issue by chdorb** [akrennmair/newsbeuter#605]
Feature proposal:

Export url to [buku](https://github.com/jarun/Buku), a command line bookmark manager.

**Comment by Minoru** [comment]
Hi! Newsbeuter isn't maintained anymore, but I'm leading a fork called [Newsboat](https://newsboat.org). 

As for the feature, it looks like one can [write a bookmarking script](https://newsbeuter.org/doc/newsbeuter.html#_bookmarking) that exports the URL. Am I missing anything?

**Comment by chdorb** [comment]
Hi,

Indeed write a plugin for bookmarking is very easy, I didn't know this feature.
I'll switch to Newsboat.

Thank you.
