### ISSUE TITLE
Google Reader support?

### ISSUE THREAD

**Issue by uzsolt** [akrennmair/newsbeuter#63]
As maybe you know GoogleReader will available only until july 1, 2013.
I'm using newsbeuter to GR (faster and simplier as GR).
Maybe want to know which can we use instead of GR.
I've found http://www.feedly.com/ - but newsbeuter is better :)

I think would be good if you (and the users, and me of course) will find a similar solution and integrate into newsbeuter.

**Comment by apheleia** [comment]
+1 for feedly

**Comment by Hund** [comment]
So, basically the developer totally ignores user demands and goes with the option he likes or whatever?

+1 for Feedly.

**Comment by clauseggers** [comment]
+1 Feedly

**Comment by apheleia** [comment]
It _might_ be an issue with the API keys and feedly ... But either case, this should be clarified in my opinion.

**Comment by jose1711** [comment]
https://github.com/Jarkore/Feednix - so there probably is a way how to do it

**Comment by clauseggers** [comment]
Feednix is using developer tokens which expire every three months. Not an optimal solution.

**Comment by annndrey** [comment]
Hi all! Feedly has OPML export option, and newsbeuter has an import option.

**Comment by jose1711** [comment]
@anndrey this way does not track (un)read status
