### ISSUE TITLE
Breakage of highlight-article with introduction of listnormal_unread

### ISSUE THREAD

**Issue by nullsym** [akrennmair/newsbeuter#92]
newsbeuter 2.7 introduced two new elements; listnormal_unread and listfocus_unread. As it can be seen on lines 71-73 [here][1] I had configured newsbeuter to change the color of articles in a feed based on their url (I have an rss feed based on combined subreddits and want to make some of those subreddits easily identifiable based on their color). This worked perfectly in newsbeuter 2.6, but as of 2.7 the color setting of listnormal_unread and listfocus_unread take precedence, thus, rendering highlight-article ineffective. 

It would be nice newsbeuter could have a **point based system** to see which color setting should take precedence, as this would be more flexible and also allow me to fix an annoyance on my config where  **highlight-article** takes precedence over **color listfocus**

[1]: https://gist.github.com/ballmerpeak/ec50df4b368294b7d4ca

**Comment by Minoru** [comment]
This was recently fixed: 743409ec6a
